### ISSUE TITLE
시세와 함게 종목명도 가져올 수 있는 방법 있을까요?

### ISSUE THREAD

**Issue by WonSeokChoi-Unicorn** [FinanceData/FinanceDataReader#103]
price = FinanceDataReader.DataReader('005930', '20211012', '20211012', exchange='KRX')

삼성전자의 2021년 10월 12일 시세를 가져오는 명령인데,

나오는 결과에서 "삼성전자"라는 종목명을 가져올 수 있는 명령어가 있을까요?

price.name, price.text 등등

없다면 기능 추가 계획 있을 지도 문의합니다.

**Comment by dlfrnaos19** [comment]
회사 코드와 이름 받아오는 코드로 직접 구성하셔서 일단 사용하시면 어떨까요

**Comment by WonSeokChoi-Unicorn** [comment]
> 회사 코드와 이름 받아오는 코드로 직접 구성하셔서 일단 사용하시면 어떨까요

전 라이브러리 자체에 이름을 반환하는 기능이 있는데, 제가 모르나 싶어서 문의했는데, 아직 기능이 없으면 알려주신대로 사용해야 되겠네요.

**Comment by WonSeokChoi-Unicorn** [comment]
좀 지나긴 했지만 공유 차원에서 적어 봅니다.

            # 한국 증권 거래소
            stockex = 'KRX'
            # 한국 증권 거래소의 리스트 가져오기
            stocks = fdr.StockListing(stockex)
            # 주식 리스트
            stockcode = [
                         '005930',# 삼성전자 005930 코스피
                        ]
            # 주식 코드로 주식명 찾기
            for stock1 in stockcode:
                # Dataframe 형태로 가져옴
                stockname = stocks[stocks['Symbol'] == stock1]
                # 이름을 리스트에 추가
                finalstockname.append(stockname['Name'].values[0])
                # 오류로 인해 이전 자료 가져올까바 Dataframe 삭제
                del[[stockname]]
