### ISSUE TITLE
암호 화폐는 오전 9시 이전에는 값을 못 불러 올까요?

### ISSUE THREAD

**Issue by WonSeokChoi-Unicorn** [FinanceData/FinanceDataReader#104]
DataReader('XRP/KRW', '20211012', '20211012')

하니 오전 9시 이전에는 빈 데이타프레임을 반환합니다.

암호 화폐는 24시간 거래되니 빈 값이 없음에도 불구하고요.

이 건 개선이 안 될 지?

제가 잘 못 처리하고 있는 것인지?

문의합니다.

**Comment by WonSeokChoi-Unicorn** [comment]
특별한 해법이 없는 것 같아서 아래와 같이 대체하였습니다.

import pyupbit
currentprice = pyupbit.get_current_price('KRW-XRP')

**Comment by FinanceData** [comment]
이전 investing에서 데이터를 가져오던 것을 yahoo 로 전환하였습니다.

https://github.com/FinanceData/FinanceDataReader/wiki/Release-Note-0.9.50
