### ISSUE TITLE
KRX symbol list Error

### ISSUE THREAD

**Issue by whodelyou** [FinanceData/FinanceDataReader#107]
codes = fdr.StockListing('KRX')
실행 시 아래와 같은 에러가 발생합니다. 

네이버 홈페이지 구조가 변경된걸로 추정됩니다. 

ValueError                                Traceback (most recent call last)
~/tmp/ipykernel_11724/1300570759.py in <module>
----> 1 codes = fdr.StockListing('KRX')

/var/mobile/Containers/Data/Application/4BA0ACFC-BF08-414E-AC4F-E0551BFBD2B0/Library/lib/python3.9/site-packages/FinanceDataReader/data.py in StockListing(market)
     60         return NaverStockListing(market).read()
     61     if market in [ 'KRX', 'KOSPI', 'KOSDAQ', 'KONEX']:
---> 62         return KrxStockListing(market).read()
     63     if market in [ 'KRX-DELISTING' ]:
     64         return KrxDelisting(market).read()

/var/mobile/Containers/Data/Application/4BA0ACFC-BF08-414E-AC4F-E0551BFBD2B0/Library/lib/python3.9/site-packages/FinanceDataReader/krx/listing.py in read(self)
     28                             '홈페이지':'HomePage', '지역':'Region', }
     29         df_listing = df_listing.rename(columns = cols_ren)
---> 30         df_listing['Symbol'] = df_listing['Symbol'].apply(lambda x: '{:06d}'.format(x))
     31         df_listing['ListingDate'] = pd.to_datetime(df_listing['ListingDate'])
     32 

/private/var/containers/Bundle/Application/0BD6F591-E3B9-4508-8886-6FFBD5E1E255/Carnets-sci.app/Library/lib/python3.9/site-packages/pandas-1.3.4-py3.9-macosx-11.5-x86_64.egg/pandas/core/series.py in apply(self, func, convert_dtype, args, **kwargs)
   4355         dtype: float64
   4356         """
-> 4357         return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
   4358 
   4359     def _reduce(

/private/var/containers/Bundle/Application/0BD6F591-E3B9-4508-8886-6FFBD5E1E255/Carnets-sci.app/Library/lib/python3.9/site-packages/pandas-1.3.4-py3.9-macosx-11.5-x86_64.egg/pandas/core/apply.py in apply(self)
   1041             return self.apply_str()
   1042 
-> 1043         return self.apply_standard()
   1044 
   1045     def agg(self):

/private/var/containers/Bundle/Application/0BD6F591-E3B9-4508-8886-6FFBD5E1E255/Carnets-sci.app/Library/lib/python3.9/site-packages/pandas-1.3.4-py3.9-macosx-11.5-x86_64.egg/pandas/core/apply.py in apply_standard(self)
   1096                 # List[Union[Callable[..., Any], str]]]]]"; expected
   1097                 # "Callable[[Any], Any]"
-> 1098                 mapped = lib.map_infer(
   1099                     values,
   1100                     f,  # type: ignore[arg-type]

/private/var/containers/Bundle/Application/0BD6F591-E3B9-4508-8886-6FFBD5E1E255/Carnets-sci.app/Library/lib/python3.9/site-packages/pandas-1.3.4-py3.9-macosx-11.5-x86_64.egg/pandas/_libs/lib.pyx in pandas._libs.lib.map_infer()

/var/mobile/Containers/Data/Application/4BA0ACFC-BF08-414E-AC4F-E0551BFBD2B0/Library/lib/python3.9/site-packages/FinanceDataReader/krx/listing.py in <lambda>(x)
     28                             '홈페이지':'HomePage', '지역':'Region', }
     29         df_listing = df_listing.rename(columns = cols_ren)
---> 30         df_listing['Symbol'] = df_listing['Symbol'].apply(lambda x: '{:06d}'.format(x))
     31         df_listing['ListingDate'] = pd.to_datetime(df_listing['ListingDate'])
     32 

ValueError: Unknown format code 'd' for object of type 'str'

**Comment by FinanceData** [comment]
0.9.3x 에서 픽스 하였습니다. 감사합니다.
