### ISSUE TITLE
The SOX index doesn't load.

### ISSUE THREAD

**Issue by adfskj** [FinanceData/FinanceDataReader#115]
Suggested solution: 
Edit /FinanceDataReader/investing/data.py line #96 : 
Add 'SOX', to the list: 
exp_syms = ['US500',  'RUTNU', 'VIX', 'SOX', ] # exceptial symbols (vol == 0)

**Comment by adfskj** [comment]
Edit:
From 0.9.50, the list of "exceptional symbols" has moved to:
/FinanceDataReader/yahoo/data.py line #12 ~18 and is now called "symbol_map = {....}"
Added 'SOX': '^SOX',  to the list and it works. 

Please include SOX for the next revision.

**Comment by FinanceData** [comment]
다음을 테스트 해보시기 바랍니다.

```python
fdr.DataReader('^SOX')
```
