### ISSUE TITLE
애플 2월 29일 "Change"데이터 이상

### ISSUE THREAD

**Issue by KIMNAMHUN00** [FinanceData/FinanceDataReader#118]
![image](https://user-images.githubusercontent.com/53559474/154689764-8804fec9-4316-4fe2-b016-26617f5d3812.png)

2016년 2월 29일의 "Change"데이터가 이상합니다.

혹시 어느 사이트에서 크롤링 하는지 알 수 있을까요?

**Comment by FinanceData** [comment]
https://www.investing.com/ 에서 데이터를 가져옵니다.
라이브러리에서는 데이터 자체를 수정하거나 정정않고 그대로 가져옵니다.

https://www.investing.com/equities/apple-computer-inc-historical-data

![image](https://user-images.githubusercontent.com/806717/157779227-dccdcfd6-2928-49d4-a48a-271b814269f8.png)

**Comment by FinanceData** [comment]
의견 제안 있으시면 알려주세요.
