### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by WonSeokChoi-Unicorn** [FinanceData/FinanceDataReader#119]
홍콩 주식에 대해서 아래와 같이 처리하는데

price = fdr.DataReader(stock2, today, today, exchange=stockex)

아래와 같은 오류가 발생합니다.

Traceback (most recent call last):
...
    price = fdr.DataReader(stock2, today, today, exchange=stockex)
  File "C:\Python39-32\lib\site-packages\FinanceDataReader\data.py", line 41, in DataReader
    df = reader(symbol, start, end, exchange, data_source).read()
  File "C:\Python39-32\lib\site-packages\FinanceDataReader\investing\data.py", line 62, in read
    curr_id = self._get_currid_investing(self.symbol, self.exchange, self.data_source)
  File "C:\Python39-32\lib\site-packages\FinanceDataReader\investing\data.py", line 30, in _get_currid_investing
    jo = json.loads(r.text)
  File "C:\Python39-32\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python39-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

홍콩 주식은 변경 사항이 있어서 안 되는 것이 정상일까요?

**Comment by leedoe** [comment]
저도 방금 같은 오류 확인했는데 investing.com에서 가져오는 모든 데이터를 못가져오는 것 같습니다

**Comment by leedoe** [comment]
header에 User-Agent를 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0로 바꿔주면 잘 되는 것 같습니다

**Comment by WonSeokChoi-Unicorn** [comment]
> header에 User-Agent를 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0로 바꿔주면 잘 되는 것 같습니다

C:\Python39-32\lib\site-packages\FinanceDataReader\investing\data.py 에서 수정해야 된다는 뜻일까요?

**Comment by leedoe** [comment]
> > header에 User-Agent를 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0로 바꿔주면 잘 되는 것 같습니다
> 
> C:\Python39-32\lib\site-packages\FinanceDataReader\investing\data.py 에서 수정해야 된다는 뜻일까요?

넵! 2개있는데 둘다 바꿔주세요!
혹시 모르니까 listing.py에 있는 header도 바꿔주시면 좋을 것 같습니다

**Comment by WonSeokChoi-Unicorn** [comment]
> > > header에 User-Agent를 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0로 바꿔주면 잘 되는 것 같습니다
> > 
> > 
> > C:\Python39-32\lib\site-packages\FinanceDataReader\investing\data.py 에서 수정해야 된다는 뜻일까요?
> 
> 넵! 2개있는데 둘다 바꿔주세요! 혹시 모르니까 listing.py에 있는 header도 바꿔주시면 좋을 것 같습니다

알려주셔서 감사합니다.

남은 하루도 행복하게 보내세요.

**Comment by simtol99** [comment]
위에 내용으로 header를 수정하니
전  ValueError: No tables found 나고 있습니다
다들 잘 되고 있으신지요?

**Comment by simtol99** [comment]
참고로 data.py에는
headers 부분이 두 군데 있으니 참고하세요

**Comment by FinanceData** [comment]
0.9.31 >> 0.9.32

전체적으로 데이터를 가져오지 못하는 문제여서 긴급히 패치하였습니다.  
(investing에 변화가 있었던 것으로 보이며, 위에서 언급하신 User-Agent 수정하였습니다)

다음과 같이 업데이트 설치하시면 되겠습니다.

```python
pip install -U finance-datareader
```

**Comment by WonSeokChoi-Unicorn** [comment]
> 0.9.31 >> 0.9.32
> 
> 전체적으로 데이터를 가져오지 못하는 문제여서 긴급히 패치하였습니다. (investing에 변화가 있었던 것으로 보이며, 위에서 언급하신 User-Agent 수정하였습니다)
> 
> 다음과 같이 업데이트 설치하시면 되겠습니다.
> 
> ```python
> pip install -U finance-datareader
> ```

빠르게 수정해주셔서 감사합니다.

크롤링이나 API 관련 코드들은 유지보수가 너무나도 중요하네요.

**Comment by dooki114** [comment]
감사합니다!

**Comment by ksch7707** [comment]
좋은 프로그램 감사히 잘 쓰고 있습니다.
위에서 말씀하신 대로 upgrade ( 0.9.32) 하고 header 도 고쳤는데도 'KS11', 'KR1YT=RR', 'US10YT=X', ... 등은 작동이 안됩니다.  def read(self): 의 
r = requests.post 값이 r= <Response [429]> 로 뜨면서 "raise ValueError("No tables found")" 메세지와 함께 죽습니다. 바쁘시겠지만 check 부탁 드립니다.
감사합니다.

**Comment by FinanceData** [comment]
아래 내용이 모두 동작하는 것을 확인하였습니다 (구글 Colab)

```python
!pip install -U finance-datareader

import FinanceDataReader as fdr

fdr.DataReader('KS11', '2020')
fdr.DataReader('KR1YT=RR', '2020')
fdr.DataReader('US10YT=X', '2020')
```

참고로 429 는 Too Many Requests 입니다.

429 응답을 말씀해주신 분들이 종종 있는데 현재 재현이 되지 않고 있습니다.
좀 더 살펴보고 파악되는 대로 댓글 드리겠습니다.

**Comment by ksch7707** [comment]
빠른 응답에 감사드립니다.
혹시 너무 빠르게 데이터를 요청해서 에러가 생기나 해서 타임슬립을  2초 정도 주어도 같은 에러가 반복 되고 있습니다.
컴퓨터에 따라 다르게 반응 한다면 혹시 python version 문제 일까요?

**Comment by ksch7707** [comment]
조금 전부터 잘 작동 되기 시작 했습니다. 왜 이런 현상이 생겼었는지는 이해가 
안되지만 지금은 잘 됩니다.  친절한 답변과 빠른 조치에 감사드립니다.

**Comment by FinanceData** [comment]
> 조금 전부터 잘 작동 되기 시작 했습니다. 왜 이런 현상이 생겼었는지는 이해가 안되지만 지금은 잘 됩니다. 친절한 답변과 빠른 조치에 감사드립니다.

답글 감사합니다. 429 Too Many Requests 응답은 서버측(investing)의 정책적인 문제로 보입니다.  클라이언트 문제(파이썬 버전, 운영체제 등)의 문제는 아닌듯 합니다.
