### ISSUE TITLE
s&p BRK-B 데이터를 읽을때

### ISSUE THREAD

**Issue by lalamango** [FinanceData/FinanceDataReader#12]
Berkshire Hathaway 데이터를 읽고자 할때

StockListing 에서는 BRK-B로 읽히고

Datareader 에서는 'BRKb'로 symbol 을 입력해야하는데 

arguemnt를 Upper로 변환 시켜서 오류가 생기는 듯 싶습니다.

input 이 'BRK-B'가 되면 

`for row in jo['All']:
            if row['symbol'] == symbol.upper():
                return row['pair_ID']
        return None`

문제가 생깁니다.

수정 되여야 할 이슈라면 request를 보내도 될가요?

**Comment by FinanceData** [comment]
following two symbols have an special chraracter(.)

* BRK.B | Berkshire Hathaway | Financials | Multi-Sector Holdings
* BF.B | Brown-Forman Corp. | Consumer Staples | Distillers & Vintners

BRK.B, BF.B 종목에 특수 문자 (.)이 포함되어 Datareader 와 일치하지 않음 범용적으로 사용하기 위해 특수 문자를 삭제

**Comment by FinanceData** [comment]
특수문자(.) 제거

* BRK.B -->  BRKB
* BF.B --> BFB
