### ISSUE TITLE
fdr.StockListing('ETF/US')

### ISSUE THREAD

**Issue by WonSeokChoi-Unicorn** [FinanceData/FinanceDataReader#121]
이번 패치에 수정 안 된 부분 같습니다.

실행하면 

'NoneType' object has no attribute 'tbody'

라고 나옵니다.

이 부분도 패치 부탁합니다.

**Comment by Unknown0123** [comment]
API 가 차단된 듯 한데 풀어주셨으면 합니다. 종가데이터 받아오는 중인데 한 번 API가 차단되더니 24시간 후에 풀렸다가 그 이후로도 정지당하더니 이제는 아예 시간이 지나도 안풀리네요..   timesleep(2)로 설정했는데도 차단되었습니다.

**Comment by WonSeokChoi-Unicorn** [comment]
> API 가 차단된 듯 한데 풀어주셨으면 합니다. 종가데이터 받아오는 중인데 한 번 API가 차단되더니 24시간 후에 풀렸다가 그 이후로도 정지당하더니 이제는 아예 시간이 지나도 안풀리네요.. timesleep(2)로 설정했는데도 차단되었습니다.

FinanceDataReader는 API가 아니고, 개발자님께서는 차단하는 것이 없는 것으로 아는데요.

**Comment by FinanceData** [comment]
> 이번 패치에 수정 안 된 부분 같습니다.
> 
> 실행하면
> 
> 'NoneType' object has no attribute 'tbody'
> 
> 라고 나옵니다.
> 
> 이 부분도 패치 부탁합니다.

패치하였습니다  (0.9.32 -> 0.9.33)
(급하게 패치하면서 놓쳤던 부분인데 언급 주셔서 감사합니다)

**Comment by FinanceData** [comment]
> 



> API 가 차단된 듯 한데 풀어주셨으면 합니다. 종가데이터 받아오는 중인데 한 번 API가 차단되더니 24시간 후에 풀렸다가 그 이후로도 정지당하더니 이제는 아예 시간이 지나도 안풀리네요.. timesleep(2)로 설정했는데도 차단되었습니다.

@WonSeokChoi-Unicorn  님의 언급대로 FinanceDataReader는 크롤링 라이브러리이므로 차단을 하거나 권한 관리를 하는 부분은 없습니다.  
참고로 지금까지 FinanceDataReader 를 사용하면서 sleep()을 해줘야 하는 경우는 없었습니다.

예외 발생했을 때 메시지를 알려주시면 도움이 될것 같습니다.

다시 차단이 된다면, 이때 동일한 내용을 "구글 Colab"에서도 확인해 보시기 바랍니다.
