### ISSUE TITLE
존재하지 않는 종목 

### ISSUE THREAD

**Issue by jaewoo-so** [FinanceData/FinanceDataReader#128]
kospi 로 종목 가져오면, 종목명 중에 '0003021C' 와 같은 것들이 있습니다. 

ex) 00004217 , 00121218, 00306217, 0048721A ...

종목 검색해도 안 나오고, 주가를 가져올 수도 없는데 이러한 것들은 무엇인가요?

**Comment by FinanceData** [comment]
이렇게 사용하신 것인가요? 

```
stocks = fdr.StockListing('KOSPI') 
```

재현이 되지 않는데요, 사용하신 코드를 알려주시면 감사합니다.
