### ISSUE TITLE
ModuleNotFoundError: No module named 'FinanceDataReader'

### ISSUE THREAD

**Issue by los0731** [FinanceData/FinanceDataReader#14]
Mac을 사용중이고, `pip install -U finance-datareader` 를 통해서 `finance-datareader 0.7.2`가 성공적으로 설치가 되었습니다. 터미널에서 `python3`을 구동후 finance-datareader을 불러오면 정상적으로 동작하는데요. 
```
>>> import FinanceDataReader as fdr
>>> fdr.__version__
'0.7.2'
```

`file.py`를 생성해서 호출하면 `ModuleNotFoundError`를 표시합니다. 
```
import FinanceDataReader as fdr
fdr.__version__
```
```
Traceback (most recent call last):
  File "/Users/los0731/Documents/playspace/study_pandas/data.py", line 1, in <module>
    import FinanceDataReader as fdr
ModuleNotFoundError: No module named 'FinanceDataReader'
```

어떤 차이가 있는것인지 잘 모르겠습니다.

**Comment by FinanceData** [comment]
위 문제는 환경의 문제 입니다. Anaconda 사용 혹은 Python 별도 설치 사용 등 환경에 따라 차이가 있을 수 있습니다.

1. .py 처음에 다음 라인을 추가해보세요.
#!/usr/bin/env python

2. 환경변수 PATH 와 PYTHONPATH 를 확인 해보세요.
PATH는 설정되어 있으나 PYTHONPATH 등 환경 변수가 제대로 설정되어 있지 않을 수 있습니다. 

3. .py를 직접 실행하셨다면 실제 수행된 Python의 버전을 확인할 필요가 있습니다.
python data.py 
python3 data.py 

파이썬 별도 설치의 경우, 위 라인은 Python2 아래는 Python3로  실행되었을 수 있습니다.
FinanceDataReader는 Python 2.x는 지원하지 않습니다. 


더 상세한 내용은 아래 내용을 참고 바랍니다.
https://stackoverflow.com/questions/19917492/how-to-use-pythonpath

**Comment by los0731** [comment]
말씀하신대로 하니 바로 해결되네요. 사용중인 IDE에서 바로 실행 할 경우, 환경 설정이 `python 2.`대로 실행되었던 것으로 추측됩니다. 3번에서 처럼 터미널에서 직접 `python3 data.py`으로 실행하니 문제없이 실행됩니다. 정말 감사합니다.
