### ISSUE TITLE
WTI 유 선물 인베스팅과 가격이 다른 이유

### ISSUE THREAD

**Issue by IAMNOTAHUMANBEING** [FinanceData/FinanceDataReader#140]
![image](https://user-images.githubusercontent.com/60809568/179450565-d76e1f96-0e5b-4fae-bb64-b54ea3faad97.png)
![image](https://user-images.githubusercontent.com/60809568/179450582-c188b0d0-fe4c-4e33-9838-8442d950018b.png)

사진으로 첨부하였습니다. 두 데이터의 가격이 다른 이유가 무엇인가요?

**Comment by psymoney** [comment]
각각의 산출 데이터가 참고하는 WTI 선물 가격의 거래소가 다른 것으로 확인됩니다.

FRD의 WTI유 선물 데이터는 [NYMEX](https://www.cmegroup.com/company/nymex.html)의 데이터를 기반으로 제공되고 있습니다.    
([quick reference의 상품선물 항목 참조](https://github.com/FinanceData/FinanceDataReader/wiki/Quick-Reference))
![image](https://user-images.githubusercontent.com/78402001/179457654-173933ec-607a-46de-9a7a-d61f7b4d0ce9.png)

올려주신 이미지의 WTI 선물 기준 가격은 CFD거래소 기준으로 확인됩니다.

동일 거래소의 동년동월 인도분 선물과의 비교가 필요할 것으로 보입니다.
