### ISSUE TITLE
혹시 시총을 추가해주실수 없나요?

### ISSUE THREAD

**Issue by goodgodgd** [FinanceData/FinanceDataReader#15]
일단 이런걸 찾고 있었는데 만들어주셔서 너무 감사합니다. yahoo_fix_?? 를 쓰고 있긴했는데 여기가 더 낫네요^^
기존 데이터리더를 쓰면서도 같은 아쉬움이 있었는데
거래량이 주식수로 나타나다 보니 전체주식 중에 어느정도의 비율이 거래된 것인가 하는 회전율 같은걸 계산하기가 어렵다는 것입니다.
어디서 어떻게 크롤링 하시는지 코드를 아직 안봐서 모르겠지만 혹시 가능하다면 그런 기능도 넣을 계획이 있는지요?
정확히 말하면 전체 주식수가 있으면 가장 좋을것 같습니다만.. 초면에 요구만해서 죄송합니다;;;
지금 상태로도 충분히 좋아서 일단 적용해보려합니다. 감사합니다.

**Comment by FinanceData** [comment]
국내 주식에 대한 시가총액(발생주식수)에 대한 historical data가 필요하시다면 다음 데이터 세트가 혹시 도움이 되실지도 모르겠습니다.

https://github.com/FinanceData/marcap

해외(특히 미국) 시가총액 혹은 발행주식수에 대한 historical data 는 찾지 못했습니다.

**Comment by goodgodgd** [comment]
우왓! 이미 있었군요. 감사합니다^^ 부자되세요~ㅎㅎ

**Comment by FinanceData** [comment]
API에 추가하는 방향 대신, 대체 데이터셋 활용 
https://github.com/FinanceData/marcap
