### ISSUE TITLE
혹시 한국과 미국 주요 세부지수(중공업 지수 등) 을 더 추가해줄수 있으실까요 ?

### ISSUE THREAD

**Issue by hojun-kang** [FinanceData/FinanceDataReader#16]
제목과 같습니다. 세부지수들에 대해서 더 추가해 주실 수 있으실지요

**Comment by FinanceData** [comment]
미국 지수는 종류가 많아서 희망하시는 지수의 정식 명칭 혹은 심볼을 리스트로 알려주시면 감사합니다.
국내는 정식명칭, 미국은 심볼로 알려주시면 좋습니다.

국내의 경우 "코스피 200 중공업" 등이 있으며, 미국 경우 중공업이 따로 있는지는 모르겠습니다. DJ Industrials, NASDAQ Industrials 등 산업 지수가 있으며 mid cap, small cap 별로도 종류가 다양합니다.

희망 지수들을 알려주시면 검토 후 가능한 반영하도록 하겠습니다.

**Comment by FinanceData** [comment]
구체적인 요청이 필요. 필요한 데이터에 대한 심볼을 지정해야 검토가 가능합니다.
