### ISSUE TITLE
ZG 데이터 오류가 나네요.

### ISSUE THREAD

**Issue by Sangwon91** [FinanceData/FinanceDataReader#160]
``fdr.DataReader('ZG')`` 로 로딩한 데이터가 과거와 다른 데이터가 나옵니다.
버그 수정에 참고해주시면 감사하겠습니다.

**Comment by adfskj** [comment]
'ZG' used to be the ticker for Gold, but around 17.8.2022 it stertrd loading the data for Zillow Group Inc. which uses the same ticker ZG according to yahoo finance.  I guess this has something to do with the change of data vendor to Yahoo. 
'GC=F' seems to work for the gold future prices but the volume looks a bit unreliable.

**Comment by FinanceData** [comment]
다음 내용을 검토해 보시기 바랍니다.

```python 
import FinanceDataReader as fdr 

# Zillow Group, Inc. (ZG) # https://finance.yahoo.com/quote/ZG
fdr.DataReader('ZG')

# Gold Dec 23 (GC=F) # https://finance.yahoo.com/quote/GC=F
fdr.DataReader('GC=F')
```
