### ISSUE TITLE
fdr.chart.plot에 Error가 있습니다. (BokehJS 버전 이슈)

### ISSUE THREAD

**Issue by Lastweekbro** [FinanceData/FinanceDataReader#169]
Document를 찾아본 결과,
BokehJS 2.4.3 에서는 plot_width, plot_height을 매개변수로 사용하지만,
BokehJS 3.0.2 에서는 삭제되었습니다.

본래 용도가 plot graph의 크기였으므로,

plot_width -> width
plot_height -> height 으로 변경하면 될 것 같습니다.

pr을 확인해봤을때, 다른 graphing library로 변경될 예정으로 보이지만,
변경이 반영될때까지 적용해두면 좋을 것 같습니다.

**Comment by FinanceData** [comment]
상세한 설명 감사합니다.

기반 라이브러리를 Bokeh 에서 plotly 로 변경하였습니다.
Bokeh에 대한 의존성이 없으므로 이 이슈는 닫도록 하겠습니다.

감사합니다.
