### ISSUE TITLE
타입 힌팅 추가

### ISSUE THREAD

**Issue by mirusu400** [FinanceData/FinanceDataReader#171]
해당 라이브러리에서 대부분 함수의 리턴값이 `pandas.DataFrame` 인것 같은데, 그에 대한 명시가 없어서 타입 힌팅과 인텔리센스를 지원하는 IDE에서 사용하기 불편합니다.

타입 힌팅은 파이썬 `3.5`버전부터 지원하는데, 해당 라이브러리는 파이썬 `3.2`, `3.3`, `3.4` 까지 현재 지원하고있어서 마음대로 수정해 PR을 보낼 수도 없는 노릇이여서 이슈로 해당 문제를 남겨봅니다

혹시 하위 버전에 대한 지원을 종료하고 타입 힌팅 기능을 추가할 생각이 있으신지 해당 이슈를 통해 여쭤봅니다.

**Comment by FinanceData** [comment]
좋은 제안 감사합니다. 3.5 이상 지원으로 수정하고 최상위 API에 일부 힌팅을 적용하였습니다.

감사합니다.
