### ISSUE TITLE
1시/30분 단위 데이터

### ISSUE THREAD

**Issue by CoKap-ASL-DEV** [FinanceData/FinanceDataReader#175]
1시/30분 단위 데이터는 받을 수 없나요?

**Comment by FinanceData** [comment]
1일 이하(분, 시간 등)의 데이터의 경우 현재 무료로 제공되는 사이트는 없어서 어렵습니다.

다음 내용을 검토중 입니다.
* 국내 주식 종목의 과거 5영업일의 분봉 데이터 
* 암호화폐 분봉 데이터

감사합니다.
