### ISSUE TITLE
HKEX에서 조회

### ISSUE THREAD

**Issue by WonSeokChoi-Unicorn** [FinanceData/FinanceDataReader#176]
fdr.DataReader('005930', '2021-04-25', '2023-04-25')

한국 증시 조회하면 최종 데이타는 2023년 4월 25일인데

fdr.DataReader('1850', '2021-04-25', '2023-04-25', exchange = 'HKEX')

홍콩 증시 조회하면 최종 데이타는 2023년 4월 24일입니다.

investing 시절에는 2023년 4월 25일 데이타를 보여주었던 것 같은데, 야후 파이낸스로 바뀌고는 못 보여주는 것 같습니다.

현재 상황에서는 아래와 같이 종료일을 오늘로 지정해서 전 날 데이타를 가져와야 될까요?

fdr.DataReader('1850', '2021-04-25', '2023-04-26', exchange = 'HKEX')

**Comment by WonSeokChoi-Unicorn** [comment]
미국 증시도 오늘 날짜까지 해야 어제 날짜 데이타가 나옵니다.

fdr.DataReader('SBUX', '2021-04-25', '2023-04-26')

암튼오늘 날짜를 입력해도  한국 증시와 다르게 다른 증시에서는 현재 종가를 가져올 방법이 없는 것 같습니다.

**Comment by WonSeokChoi-Unicorn** [comment]
> fdr.DataReader('1850', '2021-04-25', '2023-04-26', exchange = 'HKEX')

아래와 같이 start를 명시하니 오늘 종가를 가져오는 것 같습니다.

fdr.DataReader('1850', start = '2021-04-26', exchange = 'HKEX')

**Comment by FinanceData** [comment]
업데이트 하였습니다 (v0.9.62)

```
fdr.DataReader('HKEX:1850', '2021-04-25', '2023-04-26')
fdr.DataReader('SBUX', '2021-04-25', '2023-04-26')
fdr.DataReader('SBUX', '2023-04-26', '2023-04-26') # 같은 날짜
```

위 수행에서 모두 2023-04-26 데이터를 포함하도록 시간 계산식을 수정하였습니다.

감사합니다.

**Comment by WonSeokChoi-Unicorn** [comment]
> 업데이트 하였습니다 (v0.9.62)
> 
> ```
> fdr.DataReader('HKEX:1850', '2021-04-25', '2023-04-26')
> fdr.DataReader('SBUX', '2021-04-25', '2023-04-26')
> fdr.DataReader('SBUX', '2023-04-26', '2023-04-26') # 같은 날짜
> ```
> 
> 위 수행에서 모두 2023-04-26 데이터를 포함하도록 시간 계산식을 수정하였습니다.
> 
> 감사합니다.



사소한 건이지만 업데이트 해주셔서 감사합니다.
