### ISSUE TITLE
fdr.StockListing('KRX') 로 현시되는 목록이 변경되었나요?

### ISSUE THREAD

**Issue by timesavingbee** [FinanceData/FinanceDataReader#177]
메뉴얼 등에 나오는 내용과 달라졌네요?
업종 정보를 알고 싶은데, 없어졌구요..ㅠ
확인 부탁드립니다.

![image](https://user-images.githubusercontent.com/130218840/235279259-fb65ab06-d706-4dfd-8e90-2cd27a11175d.png)

**Comment by iburn78** [comment]
stocks = fdr.StockListing('KRX-DESC') # 한국거래소: 7,632 종목
으로 검색하면 됩니다.

**Comment by FinanceData** [comment]
앞서 @iburn78 님이 언급해주신 바와 같이 다음 두 가지를 구분하여 사용해보시면 되겠습니다.

```python
stocks = fdr.StockListing('KRX') 
stocks = fdr.StockListing('KRX-DESC') 
```
