### ISSUE TITLE
1996-01-25일 이전 데이터는 다운이 안되네요~

### ISSUE THREAD

**Issue by HyukWee** [FinanceData/FinanceDataReader#18]
df = fdr.DataReader('005930', '1992-01-01', '2000-10-31')

위와 같이 했을때, 데이터 갯수는 5000개가 넘지 않는데, 1996-01-25일 데이터 부터 다운이 됩니다.

1992년 데이터 부터 받고 싶은데 방법이 없나요?

**Comment by HyukWee** [comment]
혹시 도와주실수 없으실까요??

**Comment by FinanceData** [comment]
아쉽지만 현재 1996년 이전 데이터 조회 가능한 곳(웹 사이트)이 없습니다.
한국거래소(KRX)도 1996.01.01 부터 데이터를 제공하며, 네이버 파이낸스도 1996년 부터 제공합니다.

**Comment by FinanceData** [comment]
조회 개수의 한계 문제가 아니라 원천 데이터의 제약 입니다.

https://financedata.github.io/marcap/ 데이터는 전종목 1995년 부터 제공합니다.

**Comment by HyukWee** [comment]
친절한 회신 감사합니다.
 
잘 사용하겠습니다.
 
 
-----Original Message-----
