### ISSUE TITLE
인도거래소 관련문의

### ISSUE THREAD

**Issue by Yoontae6719** [FinanceData/FinanceDataReader#181]
혹시 인도 거래소도 데이터를 추출할 수 있는지 여부가 궁금합니다.

**Comment by FinanceData** [comment]
현재는 제공하고 있지 않습니다.
혹시 인도 거래소 혹은 인도 거래소 개별종목 관련하여 자주 사용하시는 데이터소스를 알려주시면 가능한지 검토해보도록 하겠습니다.
