### ISSUE TITLE
HTTP Error 404: Not Found  - symbol "US1MT=X"not found or invalid periods 채권수익률 오류 

### ISSUE THREAD

**Issue by Mintsong42** [FinanceData/FinanceDataReader#182]
!pip install finance-datareader
import FinanceDataReader as fdr
df = fdr.DataReader('US1MT=X')
df

예제에 있는 채권수익률 코드 실행시 다음과 같은 에러를 리턴합니다.

HTTP Error 404: Not Found  - symbol "US1MT=X"not found or invalid periods

**Comment by FinanceData** [comment]
미국국채 금리는 다음과 같이 FRED에서 가져오세요.
다음 심볼을 사용합니다 'DGS1'(1년), 'DGS2'(2년), 'DGS5'(5년), 'DGS7'(7년), 'DGS10'(10년), 'DGS20'(10년), 'DGS30'(30년)

```python
# 미국 1년
df = fdr.DataReader('FRED:DGS1', '2020-01-01') 

# 미국채 10년
df = fdr.DataReader('FRED:DGS10', '2020-01-01') 

# 미국 장단기 금리차 비교하기
df = fdr.DataReader('FRED:DGS10,DGS2', '2020-01-01')
df
```
