### ISSUE TITLE
해외지수중 CSI300, STOXX50 조회시 404 에러가 뜹니다.

### ISSUE THREAD

**Issue by sistocisa** [FinanceData/FinanceDataReader#184]
안녕하세요? 서비스 감사히 잘 이용하고 있습니다.
6월말까지는 해외지수 조회가 잘 되었는데,
오늘 확인해보니 CSI300, STOXX50 가 조회가 되지 않네요.
다우지수는 조회가 잘 됩니다.
0.9.50 버전 이용중입니다. 가끔 이러는 것인지 혹은 제 버전에만 문제가 있는것인지
확인부탁드립니다. 감사합니다.

**Comment by FinanceData** [comment]
데이터 소스를 investing에서 yahoo로 모두 변경하였습니다. 다음과 같이 해보시기 바랍니다.

```python
df = fdr.DataReader('YAHOO:000300.SS')
df = fdr.DataReader('YAHOO:^STOXX50E')
```
