### ISSUE TITLE
FRED 장단기금리차 티커 및 호출방식 변경 등

### ISSUE THREAD

**Issue by sorryggg** [FinanceData/FinanceDataReader#186]
Wiki 에 나온대로 하려고하니 에러가 발생하였고 아래와 같은 형태로 호출하니 정상동작하였습니다.
FRED 에서 호출 url 의 티커가 변경된 것으로 추정됩니다.

미국 장단기금리차 장기금리(10년물 국채 수익률) – 단기금리(2년물 국채 수익률)
df = fdr.DataReader('FRED:T10Y2Y', '2020-01-01','2023-08-01')

print(df)

**Comment by FinanceData** [comment]
상세한 설명과 테스트 감사합니다.

말씀 주신 내용을 반영하고, 업데이트 하였습니다.
[Release Note 0.9.61](https://github.com/FinanceData/FinanceDataReader/wiki/Release-Note-0.9.61)
