### ISSUE TITLE
 'JSONDecodeError' is not defined 이슈

### ISSUE THREAD

**Issue by sh0116** [FinanceData/FinanceDataReader#187]
File /lib/python3.11/site-packages/FinanceDataReader/naver/listing.py:52, in NaverStockListing.read(self)
     50     r = requests.get(url, headers=headers)
     51     jo = json.loads(r.text)
---> 52 except JSONDecodeError as e:
     53     print(r.text)
     54     raise Exception(f'{r.status_code} "{r.reason}" Server response delayed. Retry later.')

NameError: name 'JSONDecodeError' is not defined

Defined가 안되어있는 문제인데 혹시 주피터에서 실행해서 생기는 문제일까요? 😊

**Comment by FinanceData** [comment]
import 가 되어 있지 않아서 생기는 not defined 는 수정하였습니다.
어떤 호출하셨는지 알려주시면 문제를 파악하는데 더 도움이 될 것 같습니다.
