### ISSUE TITLE
fdr.EtfListing("KR") doesn't work

### ISSUE THREAD

**Issue by hjlgood** [FinanceData/FinanceDataReader#19]
아래와 같이 코드를 작성하면 에러가 발생합니다. .

`
import FinanceDataReader as fdr
df_etf = fdr.EtfListing('KR')
`

`
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
f:\gdrive\Programming\python\z\stock\practice.py in 
      1 
----> 2 df_etf = fdr.EtfListing('KR')

C:\Python\lib\site-packages\FinanceDataReader\data.py in EtfListing(country)
     28 def EtfListing(country='KR'):
     29     if country.upper() == 'KR':
---> 30         return NaverEtfListing().read()
     31     return InvestingEtfListing(country).read()

C:\Python\lib\site-packages\FinanceDataReader\naver\listing.py in read(self)
     11     def read(self):
     12         url = 'https://finance.naver.com/api/sise/etfItemList.nhn'
---> 13         df = json_normalize(json.loads(requests.get(url).text), ['result', 'etfItemList'])
     14         rename_cols = {
     15             'amonut':'Amount', 'changeRate':'ChangeRate', 'changeVal':'Change',

C:\Python\lib\site-packages\pandas\io\json\normalize.py in json_normalize(data, record_path, meta, meta_prefix, record_prefix, errors, sep)
    260                 records.extend(recs)
    261 
--> 262     _recursive_extract(data, record_path, {}, level=0)
    263 
    264     result = DataFrame(records)

C:\Python\lib\site-packages\pandas\io\json\normalize.py in _recursive_extract(data, path, seen_meta, level)
    233 
    234                 _recursive_extract(obj[path[0]], path[1:],
--> 235                                    seen_meta, level=level + 1)
    236         else:
    237             for obj in data:

C:\Python\lib\site-packages\pandas\io\json\normalize.py in _recursive_extract(data, path, seen_meta, level)
    236         else:
    237             for obj in data:
--> 238                 recs = _pull_field(obj, path[0])
    239 
    240                 # For repeating the metadata later

C:\Python\lib\site-packages\pandas\io\json\normalize.py in _pull_field(js, spec)
    183                 result = result[field]
    184         else:
--> 185             result = result[spec]
    186 
    187         return result

TypeError: string indices must be integers`
`

**Comment by FinanceData** [comment]
윈도우+Anaconda 환경, Colab 등에서 확인했으나 잘 실행됩니다.
사용하시는 환경과 pandas 혹은 numpy 의 버전을 알려주시면 감사합니다.

너무 낮은 버전의 pandas를 사용하고 계시다면 다음과 같이 업그레이드하는 것도 고려해 보시기 권해 들비니다.

> pip install --upgrade pandas

**Comment by FinanceData** [comment]
재현 불가. 정상 실행되는 것을 확인하였습니다 (pandas 낮은 버전의 문제로 추정)
