### ISSUE TITLE
필라델피아 반도체 지수는 지원 안될가요?

### ISSUE THREAD

**Issue by mixcheck** [FinanceData/FinanceDataReader#194]
거래소는 INDEXNASDAQ인데 NASDAQ Stock Listing하면 필라델피아 반도체 지수는 없더라구요.

Yahoo Finance에서 SOX인데 거기서도 안 긁어지고 혹시 확인 해주시면 감사하겠습니다.

**Comment by FinanceData** [comment]
현재 지원되고 있으며, 아래와 같이 심볼을 사용하시면 되겠습니다.

```python
import FinanceDataReader as fdr

df = fdr.DataReader('^SOX', '2020')
df
```
