### ISSUE TITLE
미국주식(yahoo) 데이터 관련 건의사항

### ISSUE THREAD

**Issue by jaewon-fre** [FinanceData/FinanceDataReader#196]
fdr.DataReader('AAPL','2023-09-01','2023-12-31') 와 같은 코드로 해외주식 가격, 거래량 데이터 조회하는 경우

0.9.66 버전에서는 이전 0.9.50 버전과는 다르게

Adj Close 값이 Close 값으로 대체되어서 나오고, 실제 Close 값은 나오지 않게 바뀌었는데,

기존과 같이 Close 값과 Adj Close 값 모두 나오도록 할 수는 없을까요?

![20231229_174638](https://github.com/FinanceData/FinanceDataReader/assets/106366221/2659fe28-f852-49aa-8b57-7e51d4083b06)
![20231229_174734](https://github.com/FinanceData/FinanceDataReader/assets/106366221/cca8503d-73ff-408c-82ab-868d9a8b477e)

**Comment by QuantKang** [comment]
동의합니다. 지금 Close만 수정주가로 대체되었는데, 이런 경우 Open, High, Low는 아무런 쓸모가 없어집니다.

Adj Close가 있으면 Close와 비를 구해 OHLC 모두 수정주가로 변환할 수 있습니다.

기본으로 OHLC 모두 수정 주가를 돌려주더라도, 이전처럼 OHLC + adjC를 받을 수 있는 옵션이 있는게 나을 듯 합니다.

**Comment by FinanceData** [comment]
이 부분은 내부에서도 의견이 갈렸던 분분인데, (국내종목 가격 데이터와 동일하게 형식을 맞추자는 의견)
조만간 업데이트에서는 국내 가격데이터와 `Adj Close`, `Close`을 모두 제공하도록 수정하도록 하겠습니다.
