### ISSUE TITLE
investing.com 자료 가져오는데 문제가 있나요?

### ISSUE THREAD

**Issue by dolphinwow** [FinanceData/FinanceDataReader#200]
investing.com 자료 가져오는데 문제가 있나요?

df = fdr.DataReader('FRED:NASDAQCOM,UMCSENT', start='2006', end='2010')

JSONDecodeError가 발생합니다.

**Comment by FinanceData** [comment]
다음과 같이 잘 동작하고 있습니다. 

```python
>>> df = fdr.DataReader('FRED:NASDAQCOM,UMCSENT', start='2006', end='2010')
>>> df
            NASDAQCOM  UMCSENT
DATE
2006-01-01        NaN     91.2
2006-01-03    2243.74     91.2
2006-01-04    2263.46     91.2
2006-01-05    2276.87     91.2
2006-01-06    2305.62     91.2
...               ...      ...
2009-12-28    2291.08     72.5
2009-12-29    2288.40     72.5
2009-12-30    2291.28     72.5
2009-12-31    2269.15     72.5
2010-01-01    2269.15     74.4

[1059 rows x 2 columns]
>>>
```

일시적인 문제인지 확인해봐 주시고, 
계속 문제가 있으신 경우 에러 스택 전체를 알려주시면 감사합니다.

**Comment by dolphinwow** [comment]
살펴봐 주셔서 고맙습니다.
잘 되던 코드가 갑자기 문제가 발생했습니다.
다른 라이브러리 설치과정에서 발생한 문제일 수 있지만요.
아래는 전체 에러 코드입니다.

`---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
File ~/dev/jupyter/.venv/lib64/python3.8/site-packages/requests/models.py:910, in Response.json(self, **kwargs)
    909 try:
--> 910     return complexjson.loads(self.text, **kwargs)
    911 except JSONDecodeError as e:
    912     # Catch JSON-related errors and raise as requests.JSONDecodeError
    913     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError

File /usr/lib64/python3.8/json/__init__.py:357, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    354 if (cls is None and object_hook is None and
    355         parse_int is None and parse_float is None and
    356         parse_constant is None and object_pairs_hook is None and not kw):
--> 357     return _default_decoder.decode(s)
    358 if cls is None:

File /usr/lib64/python3.8/json/decoder.py:337, in JSONDecoder.decode(self, s, _w)
    333 """Return the Python representation of ``s`` (a ``str`` instance
    334 containing a JSON document).
    335 
    336 """
--> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338 end = _w(s, end).end()

File /usr/lib64/python3.8/json/decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

JSONDecodeError                           Traceback (most recent call last)
Input In [50], in <cell line: 3>()
      1 import FinanceDataReader as fdr
----> 3 df = fdr.DataReader('FRED:NASDAQCOM,UMCSENT', start='2006', end='2010')
      4 df

File ~/dev/jupyter/.venv/lib64/python3.8/site-packages/FinanceDataReader/data.py:41, in DataReader(symbol, start, end, exchange, data_source)
     39 # Investing
     40 reader = InvestingDailyReader
---> 41 df = reader(symbol, start, end, exchange, data_source).read()
     42 end = min([pd.to_datetime(end), datetime.today()])
     43 while len(df) and df.index[-1] < end: # issues/30

File ~/dev/jupyter/.venv/lib64/python3.8/site-packages/FinanceDataReader/investing/data.py:62, in InvestingDailyReader.read(self)
     60 start_date_str = self.start.strftime('%m/%d/%Y')
     61 end_date_str = self.end.strftime('%m/%d/%Y')
---> 62 curr_id = self._get_currid_investing(self.symbol, self.exchange, self.data_source)
     63 if not curr_id:
     64     raise ValueError("Symbol unsupported or not found")

File ~/dev/jupyter/.venv/lib64/python3.8/site-packages/FinanceDataReader/investing/data.py:30, in InvestingDailyReader._get_currid_investing(self, symbol, exchange, data_source)
     25 headers = {
     26     'User-Agent':'Mozilla/5.0 (Macintosh) AppleWebKit/537.36 Chrome/98.0.4758.109',
     27     'X-Requested-With':'XMLHttpRequest',
     28 }
     29 r = requests.post(url, data={'search_text': symbol}, headers=headers)
---> 30 jo = r.json()
     31 if len(jo['quotes']) == 0:
     32     raise ValueError(f"Symbol('{symbol}') not found")

File ~/dev/jupyter/.venv/lib64/python3.8/site-packages/requests/models.py:917, in Response.json(self, **kwargs)
    915     raise RequestsJSONDecodeError(e.message)
    916 else:
--> 917     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

JSONDecodeError: [Errno Expecting value] <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="/cdn-cgi/styles/challenges.css" rel="stylesheet"><meta http-equiv="refresh" content="375"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span class="icon-wrapper"><div class="heading-icon warning-icon"></div></span><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '3',cZone: "kr.investing.com",cType: 'managed',cNounce: '73247',cRay: '8472f1192976a7bf',cHash: '5f5937ee4506505',cUPMDTk: "\/search\/service\/searchTopBar?__cf_chl_tk=IcJ4I.bPO8C1FCMindZHuK0OQbpQaz.jGwh0uJaMSKw-1705540053-0-gaNycGzNDGU",cFPWv: 'b',cTTimeMs: '1000',cMTimeMs: '375000',cTplV: 5,cTplB: 'cf',cK: "visitor-time",fa: "\/search\/service\/searchTopBar?__cf_chl_f_tk=IcJ4I.bPO8C1FCMindZHuK0OQbpQaz.jGwh0uJaMSKw-1705540053-0-gaNycGzNDGU",md: "egCsId9Vun9UHVo6v05_yy_w.3IY4cpWSmsWJx2eqUk-1705540053-1-Acen-ieKR2xibH4ftIbKe5L6zqZIEGPe1mNdNYhQQ1z-80rgBArMJag3oQxtGrlkH2DPlI6FR1Yud5_tNfkTS1sp2zA8-tQg93ZQBcxQfYWxvytNgUyGQxRrjkGzTgv1teSqtiK6jMbmlsiywtiLOgfrkVhcmWLl_6T9V6MonD6asenf_3JcOwJua7K0NDte_1ilI9-HuSrzCU1_M2xE8rmfKvy9f8uITiHhpnpaju3q6Dm4-nDu8NL77mz_Qb5egfd6v_FH02_H_hTTBrb1knanwiyaJMA1cWCU9Pny0vcdJg1iP8go-dgzJRKrf3gUq-I42iQR3d_K95NahcAzl_rXL-YNYL6GYdM1NCfKHMYjDjUDvi5aaNRHkufBTF1P6RzAf3fl3WsfU2WTD-NCu-qA0Zrf8Y9HFcffb3RVh_VTucqx7C9Oc-CNtooiNH2tzwrNg5neyahd8MA_iqSl7BgDgJq4_vNf6OSfz7MeXVj0UgV5ztSebpZBEigebDYN1jmEF_SwDy111_42kifBFOFNe8OjQvaV6GMVyU8jwc6oOqoFqqBYcDnS8nMsqqelNammiq-vFGSd6wdvoXKRSSukivdO4vmhR6HrvMqe6wRtCgTmeWfhYKQoFe1AKG2c1LIPpVpvSwZJTZns7f5ouN4nTITbfItJPCcm6VNW3OLxZHSzxfz9YuA0RcX07JokXkzuDN_pg6MUo_Oz5x8wcjYrM6fiE2eSG0U_-riXue84gLeBR4QjXhvGuuNln8YO7I89hkTwkhEbUzBh8SKZOcZa1HDwZgNkiM1nUbjx2K7Q89u1s5t7gk4hSvV_jhOqnXGMpG_Fl_nNgwZgSGugFq9_RajfiWFgCzrndIDTjRkppWOOdEZ0RQObyOgLm9PtkLAYQuVk-1qx8ciO2WTlc2CFJt-MLe_iYWssyZUHWj1wpmX7bXFsp2F2RvHGFkqK7otR2bdV4eeO9KyYa24oXst7z0oPuUsLkbhI0ehd5ztzB59mwJOh4UzEoo-nV7QvXF9VLFQjChh--wT5LDOqsoBxPLaWtsrQozsmYNnYo_m1netpMHsLaW4RaVBwKE7pMEGwE62NoYznRbX5QxwAuo-nczHNRM0cR-XLl1XzXvhtgIu1LUtUtnlsevhw_Zgl9R7tuywVJt_4E7-zNKlCw6tKRrbpn6jBEg-SrXxGBjD3vXA5nUgx6EmRjLWb2PXCdWUDh04hC5QbtWm8Iwv64z09pD6l3tF3y9tmTSmmSMiE3GWr3-fSX3douidp3hZbPbna1DWVZFxV2hlaCJZhkSP8e9c0t-NHEhfxalLNWPZORmgD26LSv6Qc4FLyuxV4qoYKxkVxieNlTrZ1N1RteUdgkeCHkILm6VeIVL0MAVESXWA3SZ3OcDg_9D1ti-3kT6jwBdcUbsCdO85xqi83HvY6T4O6X3ldW7Fy7qHKI6967nKwv7Riq1UR-rCdSMcl97rcnzyVcV2lfeIPDCGzJN_SY65vQhVRjb312bs7N8GEubYtiOt_0NoNWciEyt9qH0FGM5IkXQLQnizB-sLDI4YQv7C7Gxw87sjH4kuFZ47KUdbJXHaiLx7inEPE2wjqYwBm4TUvJkh2zMQdtHlB1f-0WZ1LhXqizx1of2O6U1lU8nQGKf-Y9S3_zW8MQnTDshh97YyG-ayNBLIzmWjzayI8Gf9RertTHHKHsQehuQvyfjGwyCDkyCZKCWe6EgIj1M9qxdNAnAdQ2DkBLuhm81tn2lYVDPp2yFLfztXISFEM1YBYIKIaev45jAqZ2XvvLpmwPxdIEiwVGoa302wjO4mp-o2yfptvQfreSiaKyvh5jHUoChf0ZXFn-W4z5ZZDc19-7gDG6mzRPLpjUx1XROdsCnFMY7qwY3sY5sjhy6NhDtvOhCMd7pMNLZJB5jHDaVv_YCCXFYjCd-QeIMrLdMeWmgL61DQKQ7luyCRuVNN-iZavM3Jvj6BduE1beR8a5MnOquL3a9aTR8hhFS63_hcPJFQVP8mKjP8kU784uzjKnPhweScF34--hnv-ORnhQpAblt4mfrAqwO2ko1gReluq-gpsBDqPCl2lWAD3f4soTArbztEQdmmUYxtfDcOwV9196xpfrojhS-VG1yvadlAdk-NYSwGf7zGGjlYIRK9k7iTWwA1LEtrOj3UH9DqCAS3Tsd6JGbtbNjvI38xDpfo0whn9AFBznMyYCCdbY0o9WWo59Ly1sxFQjCBnzNZNz08WYQD8QU44swhyrZ-6_VIOhanWnxqBYAm7vUb7HJlPMt2rFGEA2ufL3FVGOCDY8beMYd21O8wbrcd1jUsJAz_89HsdSpXR72SJXiPe1V84jLH3jqWrQqZz_Bz95HkMBNNAZ0wDGZhEYbJUaEWc2SH15Y8XvEOuihUZU-jpzbeEoofI3ud2D2TT2gstB7V42kCcL7Sk6ZmIupL0Ry5FTc-7e0EeyWqz53hu9DVy4LgdBHkIHmMMgWZC8sAQNANZ691ERwTZL6DCa3-miwqLYfnpd3v7NgFrUHIRl96kQ4SfjBaIIkoViIugo8XKw2HZ7_XpFMuiUhxSDTvWsJMEmmRW-onK4DNRE7UOKDD4DtqQ1JFfQ1uuTxrMU0dj3D2iP2-C_IRxuY7GSOv5oQYOhbAesu6JKp9-WB3NWnjZwMU4j_QyKQc7tt6pVMAj8YeokcieMGukLQqIqiA38osw7sH5hiZZJkrMXX08cje_Td4ikg8307BxaZvlqJV2SVNIoB1sCbWdh3M3bM_n938poBxLst8XSExbGb41SXu0rcLHKzs-08zkQ78REBcWnZ4pB9x5i3tJ1bvaXUjWSr0ed6KO5-3_N5R22ewjT4I1jDvQeUZwT5peZNrJe-lWsuXjNxGIDwy9zWBPpZu-upJV-CLDYthMR3VAio-oIG0dAH-HCRBDxv8JiI_ZIzRWcPPgh91I7gsUpqJAK5pffcfnPs4920HCuOWS75VAymDYCVpfDp90JGpNHKZ8F5zZ79HeT19x285uvyRGKkOke5weKMLgjEjBpBNKHBzJcjKVecJ5irxD6mAe0AsizEZCPX2jzjFEBOHx9RlEnWObn_tpsIQajtLiTShOzdHnljom8F1S",cRq: {ru: 'aHR0cHM6Ly9rci5pbnZlc3RpbmcuY29tL3NlYXJjaC9zZXJ2aWNlL3NlYXJjaFRvcEJhcg==',ra: 'TW96aWxsYS81LjAgKE1hY2ludG9zaCkgQXBwbGVXZWJLaXQvNTM3LjM2IENocm9tZS85OC4wLjQ3NTguMTA5',rm: 'UE9TVA==',d: 'fjXnIfLLTPuU/lV9QvGjEYGEQ9ZiCNetC2HkXPvrZXPrfySMhzVW11RlgTcHjjL1VOAvx+huw5omHeqUmnTbF+KDI74H3Vvi9m7RHApNdrn3oOLAlrYaSyJPO7cIeyjDE0PeM1sXfyt3K4390hAGfoJ48Mkv2BLZwaGpXymTobFMZHbKWdEWZSX7znZsjZ/twr3kGgORD1nN5aPSyCWR3nWwf/+7ipRO/U19efJO2H4nXZuQGyQlU3jRYrFZf7LQrjLqMFVWIXuK4cnMnDnqrLlg9i7ifHDSQPQJfXbx3AQfNCFbICjLcvigCHKJ3pUcBIktyQmlJcD5sAtAteaT0HL3TFwHrczvc6lnRWBSMCErD6fU1wPxfi27lXbCNidbd9I9Tsmz7dtxuEkEwll/HfUH+QoU5dQg4mYS9Fu1ss9La0t+rwhTvgo6kCOH3vAjBA7SiG1rGkM8la4CCj9LbL5LQRr4A82Vi0sfUSXFGeGWMhBNPD0znP8QxN8OVzv82cYHX1rC7PILepFA2LYrHhQqxx2HHVQEPUBhOPG2ugL0apL9RqaF3ieQP8Mx6L/B4+CigZ/R6xv8H3M1VALmyg==',t: 'MTcwNTU0MDA1My45NTgwMDA=',cT: Math.floor(Date.now() / 1000),m: 'uWqUo6bShoEYlRxAnnAJBjrFaBW5/KTCNAJOIgepvA0=',i1: '/+0Y5rKCwRVQZ64wCeh3Mg==',i2: 'Kc/UvgMSea3KH6gMoRVOfA==',zh: 'JJQg2KI/+bPgJbLHlLjmrs/mnno8aAGH5k3tm8QDk4c=',uh: 'POxlFgDekQG5h9Kd7TiU8+U9MUspCK9r8ctlJLyBZWY=',hh: 'beRzjoKRgdeiWAZwLwec6O5KPJjeUpIstTw6WGio1jY=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page/v1?ray=8472f1192976a7bf';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/search\/service\/searchTopBar?__cf_chl_rt_tk=IcJ4I.bPO8C1FCMindZHuK0OQbpQaz.jGwh0uJaMSKw-1705540053-0-gaNycGzNDGU" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>: 0`

**Comment by FinanceData** [comment]
파이썬 버전은 문제가 없으나 FinanceDataReader의 버전이 낮은 것을 쓰시는 것  같습니다. 현재는 investing이 아닌 yahoo finance에서 가져오고 있습니다. 다음과 같이 FinanceDataReader를 최신 버전으로 업데이트 하여 사용해 보시기 바랍니다.

```
pip install -U finance-datareader
```

**Comment by dolphinwow** [comment]
바쁘실텐데 답변 감사합니다.
저도 다른 곳에서 실행해보니 이상없이 가져오는 것을 확인했습니다.
제 개발 환경에 변화가 생겨 발생한 문제 같습니다.

**Comment by FinanceData** [comment]
해결 되셔서 다행입니다.
