### ISSUE TITLE
종목 리스팅 함수(StockListing())의 결과중 상장일 정보가 누락된 항목들이 있습니다.

### ISSUE THREAD

**Issue by AcornInvest** [FinanceData/FinanceDataReader#208]
종목 전체를 리스팅 하면서 각 종목의 상장일 정보를 얻으려고 하고 있습니다.

StockListing('KRX') 로 하면 상장일 정보가 없고, StockListing('KRX-DESC')로 하면 상장일 정보가 있긴한데 누락된 종목들이 많습니다.
얼핏 봐서는 우선주들이 누락된 것으로 보입니다.
2024.3.29 일에 조회한 기준으로 예를 들면

001465 BYC우

위 종목의 ListingData가 NaT 로 표시됩니다.

확인 부탁드립니다.

**Comment by FinanceData** [comment]
업종, 주요제품, 상장일, 결산월, 대표자명, 홈페이지 정보는 다음 페이지로 부터 가져오는 정보입니다.

https://kind.krx.co.kr/corpgeneral/corpList.do?method=loadInitPage

이 페이지의 정보는 "상장법인" 대한 정보이므로 우선주에 대한 정보는 없습니다.
