### ISSUE TITLE
종목 리스팅 함수(StockListing()) 로 상폐종목 정보를 받을 때 데이터가 중복되는 항목들이 있습니다.

### ISSUE THREAD

**Issue by AcornInvest** [FinanceData/FinanceDataReader#209]
stocks = fdr.StockListing('KRX-DELISTING') 으로 상폐종목들 전체의 정보를 받아오는데 아래 종목들이 두 개씩 겹쳐서 나옵니다.

      Symbol Name  Market SecuGroup Kind ListingDate DelistingDate  \
890   182690  테라셈  KOSDAQ        주권  보통주  2014-10-30    2022-10-17   
1388  182690  테라셈  KOSDAQ        주권  보통주  2013-10-11    2014-10-30   

      Symbol    Name  Market SecuGroup Kind ListingDate DelistingDate  \
894   127160  매직마이크로  KOSDAQ        주권  보통주  2015-11-19    2022-09-22   
1306  127160  매직마이크로  KOSDAQ        주권  보통주  2013-12-20    2015-11-19   

      Symbol   Name  Market SecuGroup Kind ListingDate DelistingDate  \
1042  204990  코썬바이오  KOSDAQ        주권  보통주  2016-12-09    2020-08-11   
1264  204990  현성바이탈  KOSDAQ        주권  보통주  2015-04-03    2016-12-09 

      Symbol Name  Market SecuGroup Kind ListingDate DelistingDate  \
1071  197210   리드  KOSDAQ        주권  보통주  2015-11-20    2020-05-14   
1305  197210   리드  KOSDAQ        주권  보통주  2014-09-26    2015-11-20   

각 종목들의 행 중 더 먼저의 것은 KONEX에 있다가 나중에 KOSDAQ으로 이전상장한 것으로 보입니다. 그게 맞다면 앞서의 정보는 Market을 KONEX로 수정 요청드립니다.

**Comment by FinanceData** [comment]
좋은 지적과 의견 감사합니다.

다른 시장에서 이전 상장하는 경우(KONEX -> KOSDAQ으로 )되었다가 상장폐지 되는 경우 실제 동일종목에 상장폐지가 두 번 일어 닙니다.
현재 상장폐지 내역은 다음 페이지에서 가져오지만, 여기에는 시장에 대한 정보가 없습니다. 

https://kind.krx.co.kr/investwarn/delcompany.do?method=searchDelCompanyMain

혼선 방지를 위해 
1. 아예 시장 컬럼을 제외
2. 중복의 경우 KONEX를 추가
3. 다른 더 좋은 방법
 
내부 논의를 거쳐보겠습니다.

감사합니다.
