### ISSUE TITLE
수정종가를 불러올 수 있나요?

### ISSUE THREAD

**Issue by yjaeyoon** [FinanceData/FinanceDataReader#21]
"Close"에는 종가가 담겨 있는 것 같은데 수정종가 ("Adj. Close", adjusted for stock splits and dividends)를 불러올 수 있나요? 그렇지 않다면 이게 추가될 계획이 있는지 궁금합니다.

**Comment by FinanceData** [comment]
FinanceDataReader 에서 가져오는 모든 가격 데이터는 수정 주가(Adjusted Price)입니다. 따라서, 종가(Close)역시 수정종가(Adjusted Close) 입니다.

보다 상세한 내용은 아래 내용을 추가로 참고하시기 바랍니다.

https://github.com/FinanceData/FinanceDataReader/blob/master/tutorial/FinanceDataReader_Tutorial_01_Adjusted_closing_price.ipynb

**Comment by gigascake** [comment]
최근에 수집해보니, 수정종가가 아니던데요? 액면분할한 종목의 가격이 1/5로 바뀌었는데 이전의 종가가 그대로 나오는 걸 확인했습니다.ticker는  KG케미칼  001390
