### ISSUE TITLE
전자공시 OPENDART 지원 계획은 없으신가요?

### ISSUE THREAD

**Issue by jellygit** [FinanceData/FinanceDataReader#22]
2020-01-20 부터 전자공시에서 OPEN API 제공 중인데 지원 계획이 있으신지요?
https://opendart.fss.or.kr/

**Comment by FinanceData** [comment]
관심 감사합니다.
말씀 대로 1/20부터 기존 Open API가 Open DART로 대폭 개편되어 상당히 많은 정보를 제공하고 있습니다.

개발 계획이 있고 Open DART를 검토중에 있으며 FinanceDataReader에 포함하여 업그레이드에 포함 할 예정입니다.

릴리즈 시기를 특정하기 어려우나 늦어도 2020년 3월말 이전에는 이루어 질 것입니다.
감사합니다.

**Comment by FinanceData** [comment]
새로운 오픈소스 프로젝트로 시작합니다.

https://github.com/FinanceData/OpenDartReader
