### ISSUE TITLE
S&P500은 검색이 안됩니다. 

### ISSUE THREAD

**Issue by tehryung** [FinanceData/FinanceDataReader#26]
FDR을 이용한 종목데이터 전체를 얻기 중,
S&P500은 검색이 안됩니다. 다른 건 다 되는데요.

# S&P 500 symbol list
sp500 = fdr.StockListing('S&P500')

이 부분에서 에러가 납니다. 

KeyError: "['Symbol'] not in index"

Google Colab에서 사용중 입니다.

**Comment by jamesjungcool** [comment]
wikipedia/listing.py의 'Ticker symbol' 을 'Ticker Symbol' 로 수정하면 됩니다

**Comment by FinanceData** [comment]
@jamesjungcool 코드 리뷰와 제안 댓글 감사합니다. 덕분에 손쉽게 찾았습니다.

Release 0.9.1 에서 FIX 하였습니다.
