### ISSUE TITLE
KRX 에서 6자리 코드 중 알파벳이 포함된 것은 찾지 못하는 것 같습니다.

### ISSUE THREAD

**Issue by jasmu02** [FinanceData/FinanceDataReader#28]
28513K  SK케미컬우 이외에도 6자리 코드 중에서 알파벳이 포함된 코드가 몇가지 보이는데, 이것은 찾지 못하는 것 같습니다.

**Comment by FinanceData** [comment]
현재 종목리스팅(`fdr.StockListing('KRX')`)에는 우선주 목록이 제외되어 있으며, 가격 데이터를 가져옵니다. `fdr.DataReader('28513K')`는 가능합니다.

종목리스팅 StockListing() 함수가 상장법인 목록을 가져오도록 되어 있기 때문에 우선주나 부동산 펀드 등을 포함되어 있지 않습니다. 향후 업데이트에 우선주와 부동산 펀드 목록이 포함 될 예정입니다.

**Comment by FinanceData** [comment]
FIX 하였습니다. 
추가로 우선주 종목코드를 종목리스팅에 추가하였습니다.

https://github.com/FinanceData/FinanceDataReader/wiki/Release-Note-0.9.3

**Comment by jasmu02** [comment]
수정해 주셔서 감사합니다. 주식관련된 데이터를 가지고 먼가 해보고 싶어서, 키움 API를 이용해서 해보다가, 데이터를 가져오는데 문제가 있어서, 두리번 거리다가 이곳을 알게되었고, 공부를 좀 해보고 싶어서 글을 남겼었는데, 빠르게 회신을 주셔서 감사하게 생각합니다.
