### ISSUE TITLE
FutureWarning:

### ISSUE THREAD

**Issue by partrita** [FinanceData/FinanceDataReader#37]
pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

**Comment by FinanceData** [comment]
기록 차원에서 남깁니다.  

pandas 1.0.0 (January 29, 2020)

https://pandas.pydata.org/docs/whatsnew/v1.0.0.html

> pandas.json_normalize() is now exposed in the top-level namespace. Usage of json_normalize as pandas.io.json.json_normalize is now deprecated and it is recommended to use json_normalize as pandas.json_normalize() instead (GH27586)

**Comment by FinanceData** [comment]
Release 0.9.6 (Apr 11, 2020) 에서 FIX하였습니다.
