### ISSUE TITLE
ImportError: cannot import name 'json_normalize' 오류

### ISSUE THREAD

**Issue by Jace-JaehoonKim** [FinanceData/FinanceDataReader#39]
안녕하세요!
새로운 서버컴에 설치하려니까 오류가 떠서요 확인부탁드립니다!

>>import FinanceDataReader as fdr

ImportErrorTraceback (most recent call last)
<ipython-input-5-92b003391282> in <module>
----> 1 import FinanceDataReader as fdr

/usr/local/lib/python3.6/dist-packages/FinanceDataReader/__init__.py in <module>
----> 1 from .data import (DataReader)
      2 from .data import (StockListing)
      3 
      4 from .data import (EtfListing)
      5 

/usr/local/lib/python3.6/dist-packages/FinanceDataReader/data.py in <module>
----> 1 from FinanceDataReader.investing.data import (InvestingDailyReader)
      2 from FinanceDataReader.krx.data import (KrxDelistingReader)
      3 from FinanceDataReader.naver.data import (NaverDailyReader)
      4 from FinanceDataReader.nasdaq.listing import (NasdaqStockListing)
      5 from FinanceDataReader.krx.listing import (KrxStockListing, KrxDelisting)

/usr/local/lib/python3.6/dist-packages/FinanceDataReader/investing/data.py in <module>
      3 import requests
      4 import pandas as pd
----> 5 from pandas import json_normalize
      6 from FinanceDataReader._utils import (_convert_letter_to_num, _validate_dates)
      7 

ImportError: cannot import name 'json_normalize'

**Comment by Jace-JaehoonKim** [comment]
json_normalize 이거 deprecated된것같습니다 확인해주세요!

**Comment by FinanceData** [comment]
#37 과 동일한 이슈 입니다. 

pandas가 1.0.0로 업그레이드 되면서 json_normalize 네임스페이스가 바뀌었습니다. 이에 대한 대응이 FinanceDataReader 0.9.6(현시점의 최종 버전)에 반영되었습니다.

다음과 같이 설치된 pandas 1.0.0 (or higher) 로 업그레이드 하세요.
> pip install --upgrade pandas

pandas 하위 호환성에  대한 대응(메시지 등)은 추후 업그레이드에서 검토해 보겠습니다.

**Comment by FinanceData** [comment]
Release 0.9.6 (Apr 11, 2020) 에서 FIX한 문제 때문에 발생하였습니다.

다음과 같이 설치된 pandas 1.0.0 (or higher) 로 업그레이드 하거나,

> pip install --upgrade pandas

혹은 pandas 1.0.0 미만을 반드시 사용해야하는 경우, 다음과 같이 FinanceDataReader를 downgrade 합니다.

> pip install finance-datareader==0.9.5
