### ISSUE TITLE
미국, 한국 데이터 외에 다른 시장 추가하실 계획은 없으신가요?

### ISSUE THREAD

**Issue by jugol** [FinanceData/FinanceDataReader#41]
혹시 일본, 중국, 영국 등등의 시장 데이터 (거래소 종목 리스트)에 대한 추가 계획이 있으신지 여쭤보고 싶어서 질문 드립니다. 이미 나름 모듈들이 완성 된 상태인 것으로 보여서, 목록에 대한 리스팅만 추가적으로 하면 될 것 같아서요 :)

**Comment by FinanceData** [comment]
제안 감사합니다. 
말씀하신대로 리스팅만 추가하면 대부분 조회가 가능합니다. 향후 업그레이드에서 국가별 거래소와 상품을 정리하여 업데이트 하는 방향으로 검토하겠습니다.

**Comment by FinanceData** [comment]
KRX (전체, 한국), KOSPI (코스피, 한국), KOSDAQ (코스닥, 한국), KONEX (코넥스, 한국)외에  StockListing 에 다음 심볼들이 추가되었습니다.

1. NYSE (뉴욕증권거래소, 미국)
2. NASDAQ (나스닥, 미국)
3. AMEX (미국증권거래소, 미국)
4. SSE (상하이증권거래소, 중국)
5. SZSE (심천증권거래소, 중국)
6. HKEX (홍콩증권거래소, 홍콩)
7. TSE (도쿄증권거래소, 일본)
8. HOSE (호치민증권거래소, 베트남)

더 상세한 내용은 아래 Release Note 를 참고하시기 바랍니다.

https://github.com/FinanceData/FinanceDataReader/wiki/Release-Note-0.9.10
