### ISSUE TITLE
틱 데이터

### ISSUE THREAD

**Issue by ParamountSky** [FinanceData/FinanceDataReader#48]
틱 데이터(5분봉, 15분봉 등)는 추가 계획 없으신가요?

**Comment by FinanceData** [comment]
관심과 제안 감사합니다.
저희가 아는 한, 전종목에 대한 분봉 데이터는 유료 데이터로만 가능합니다.

FinanceDataReader 는 크롤링 기능을 제공하는 라이브러리입니다(데이터 수집의 주체가 라이브러리 사용자). 데이터를 중계하거나 수보한 데이터 제3자 제공은 법적인 문제가 있어서 FinanceDataReader 의 기능으로 제공하기 어렵습니다.

다만, 공개된 분봉 데이터가 있다면 크롤링을 추가할 수 있습니다만 현재 분봉 데이터를 공개적으로 제공하는 곳은 없는 것으로 알고 있습니다.
