### ISSUE TITLE
심볼 `CL`의 경우 "WTI유 선물 (NYMEX)"이 아닌 결과가 나옵니다

### ISSUE THREAD

**Issue by everlearningemployee** [FinanceData/FinanceDataReader#50]
```python
import FinanceDataReader as fdr
df = fdr.DataReader('CL', '2020')
tmp = df['Close'].plot()
```
아래 데이터가 나오는 것 같습니다
https://kr.investing.com/equities/colgate-palmo

**Comment by FinanceData** [comment]
심볼(symbol)과 거래소(exchange)가 매칭이 되도록 수정하였습니다. 

서부 텍사스 중질유(WTI) 선물의 경우  ICE(대륙간거래소)에 상장되어 있습니다.
FinanceDataReader 를 업그레이드 하시고, 

```python
pip install -U finance-datareader
```

다음과 같이 조회하세요.

```python
fdr.DataReader('T', '2020', exchange='ICE')
```

심볼(symbol)과 거래소(exchange)가 매칭에 대한 상세한 내용은
아래 Release Note를 참고하시기 바랍니다.

https://github.com/FinanceData/FinanceDataReader/wiki/Release-Note-0.9.10
