### ISSUE TITLE
조만간 미국데이터 symbol 못 받아올거 같아요

### ISSUE THREAD

**Issue by littlehongkong** [FinanceData/FinanceDataReader#52]
old.nasdaq.com 접속해보니 아래 팝업이 뜹니다.

> d.nasdaq.com is retiring soon!
> Attention: We will be retiring old.nasdaq.com soon.
> 
> Moving forward, please visit our newly expanded Market Activity section on Nasdaq.com

**Comment by FinanceData** [comment]
예, 관심과 제안 감사합니다.

해외주식 종목 목록을 old.nasdaq.com (현재 서비스 되고 있지 않음)에서 naver finance로 변경하였습니다. 

지원되는 거래소는 다음과 같습니다.

1. KRX (전체, 한국)
2. KOSPI (코스피, 한국)
3. KOSDAQ (코스닥, 한국)
4. KONEX (코넥스, 한국)
5. NYSE (뉴욕증권거래소, 미국)
6. NASDAQ (나스닥, 미국)
7. AMEX (미국증권거래소, 미국)
8. SSE (상하이증권거래소, 중국)
9. SZSE (심천증권거래소, 중국)
10. HKEX (홍콩증권거래소, 홍콩)
11. TSE (도쿄증권거래소, 일본)
12. HOSE (호치민증권거래소, 베트남)

더 자세한 내용은 아래 Release Note를 참고하시기 바랍니다.

https://github.com/FinanceData/FinanceDataReader/wiki/Release-Note-0.9.10
