### ISSUE TITLE
pip install 후 사용시 발생하는 에러가 있습니다.

### ISSUE THREAD

**Issue by nambee** [FinanceData/FinanceDataReader#58]
안녕하세요, 좋은 package를 만들어주셔서 감사합니다.

설치 후 오류에 대하여 report하고자 글을 작성합니다.

설치 후에 아래와 같이 코드를 실행했습니다.
finance-datareader의 pip install 후에 바로 실행이 되지 않습니다.
Import error가 발생하여 beautifulsoup4와 xlrd를 추가로 설치하고 문제를 해결했습니다.
수정 자체는 pip install을 2개 더 해주니 저는 동작을 했습니다.

```
[실행 환경]
window 10
python 3.7.9
```

**처음 설치**
`pip install finance-datareader`

**실행 코드**
```
import FinanceDataReader as fdr
df = fdr.DataReader('036360', exchange='KRX-DELISTING')
print('df:',df)
```

**추가 설치**
```
pip install beautifulsoup4
pip install xlrd
```

감사합니다.

**Comment by FinanceData** [comment]
관심 감사합니다. 도움이 되시길 바랍니다.

beautifulsoup, xlrd, pandas 등이 설치되어 있다면 대분의 경우 문제가 되지 않습니다.
현재 기준으로 삼고 있는 환경은 Google Colab 과 Anaconda 환경 입니다.
파이썬과 각종 라이브러리들을 별도로 설치해주신 다면 Google Colab 과 Anaconda 환경을 참고하시면 참고가 될 듯 합니다.

감사합니다.
