### ISSUE TITLE
ModuleNotFoundError: No module named 'FinanceDataReader' 가 발생합니다

### ISSUE THREAD

**Issue by tenacityman** [FinanceData/FinanceDataReader#64]
안녕하세요.

pip 인스톨 하고 업데이트 했는데도 
Anaconda 에서  Jupyter notebook실행 후  import FinanceDataReader as fdr 하면 
ModuleNotFoundError: No module named 'FinanceDataReader' 가 발생합니다.
조언부탁드립니다.
감사합니다.

운영체제 : WIndow10
파이썬 버전 : Python 3.8.2

인스톨 pip list

Package            Version
------------------ ---------
astroid            2.3.3
beautifulsoup4     4.9.3
certifi            2020.12.5
chardet            3.0.4
colorama           0.4.3
finance-datareader 0.9.10
idna               2.10
isort              4.3.21
lazy-object-proxy  1.4.3
lxml               4.6.2
mccabe             0.6.1
numpy              1.19.4
pandas             1.1.5
pip                20.3.2
pyftpdlib          1.5.6
pylint             2.4.4
python-dateutil    2.8.1
pytz               2020.4
requests           2.25.0
requests-file      1.5.1
setuptools         41.2.0
six                1.14.0
soupsieve          2.1
tqdm               4.54.1
urllib3            1.26.2
wrapt              1.11.2
xlrd               2.0.1

**Comment by chaconne67** [comment]
아마 파이썬 설치 관련 문제이지 않을까 예상되네요. 가상환경에서 해보시면 될듯~

**Comment by tenacityman** [comment]
Virtual에서 실행해도 안되는데 다른 이유가 있을까요..? 
도움이 필요해요

(virEnvFolium) D:\>pip list
Package            Version
------------------ -------------------
beautifulsoup4     4.9.3
branca             0.4.1
certifi            2020.12.5
chardet            3.0.4
finance-datareader 0.9.10
folium             0.11.0
idna               2.10
Jinja2             2.11.2
lxml               4.6.2
MarkupSafe         1.1.1
numpy              1.19.4
pandas             1.1.5
pip                20.3.3
python-dateutil    2.8.1
pytz               2020.4
requests           2.25.0
requests-file      1.5.1
setuptools         51.0.0.post20201207
six                1.15.0
soupsieve          2.1
tqdm               4.54.1
urllib3            1.26.2
wheel              0.36.2
wincertstore       0.2


> 아마 파이썬 설치 관련 문제이지 않을까 예상되네요. 가상환경에서 해보시면 될듯~



> 아마 파이썬 설치 관련 문제이지 않을까 예상되네요. 가상환경에서 해보시면 될듯~

**Comment by FinanceData** [comment]
명령라인의 환경과 다른 환경에서 실행하신 것이 아닌가 싶습니다.

명령라인이 아닌 IPython 혹은 Jupyter Notebook 에서 다음과 같이 설치하고 import 해보시기 바랍니다.

```
!pip install finance-datareader
```

```
import FinanceDataReader as fdr
```

**Comment by FinanceData** [comment]
설치 혹은 환경에 관련한 문제로 보입니다.

IPython 혹은 Jupyter Notebook 에서 다음과 같이 설치하고 import 해보시기 바랍니다.
일단 이슈 클로징합니다. 혹시 더 문제가 발생하면 이 이슈를 reopen 해주세요~

```
!pip install finance-datareader
```

```
import FinanceDataReader as fdr
```

감사합니다.

**Comment by jwkwon0817** [comment]
저도 같은 문제를 겪고 있습니다. 다만 pip로 설치한 것들은 jupyter notebook에서 실행이 안됩니다. 어떻게 해결하나요?
