### ISSUE TITLE
key error 'industry'

### ISSUE THREAD

**Issue by ChangjinHan** [FinanceData/FinanceDataReader#66]
# S&P500 종목 리스트
```
import FinanceDataReader as fdr

sp500 = fdr.StockListing('S&P500')
sp500.head()
```
위와 같은 코드를 실행할 때 KeyError: "['Industry'] not in index" 가 발생합니다.
아마도 크롤링하는 사이트에 변화가 생긴게 아닐까 생각하는데
수정해주시면 감사하겠습니다!

**Comment by FinanceData** [comment]
관심 감사합니다. 말씀 하신 내용은 0.9.12 에서 FIX 되었습니다 (원천 데이터 사이트의 변경을 반영하였습니다)

다음과 같이 upgrade 하셔서 사용하세요.

```
pip install --upgrade finance-datareader
```

https://github.com/FinanceData/FinanceDataReader/wiki/Release-Note-0.9.12

**Comment by ChangjinHan** [comment]
> 관심 감사합니다. 말씀 하신 내용은 0.9.12 에서 FIX 되었습니다 (원천 데이터 사이트의 변경을 반영하였습니다)
> 
> 다음과 같이 upgrade 하셔서 사용하세요.
> 
> ```
> pip install --upgrade finance-datareader
> ```
> 
> https://github.com/FinanceData/FinanceDataReader/wiki/Release-Note-0.9.12

제가 릴리즈 노트를 확인하지 못했네요! 
빠른 업데이트 감사합니다 :)
