### ISSUE TITLE
코스닥150 지수 데이터 관련

### ISSUE THREAD

**Issue by littlehongkong** [FinanceData/FinanceDataReader#67]
국내 지수데이터 수집시 코스닥150만 하루정도 갭차이가 나는데, 혹시 원인이 어떤게 있을까요?

**Comment by FinanceData** [comment]
KODEX 코스닥 150 (229200) 

네이버증권의 데이터와 함께 비교를 해보았습니다. 아래 값들을 비교해 보시면 동일한 것을 확인할 수 있습니다.

https://finance.naver.com/item/sise.nhn?code=229200 (네이버 증권)
![](https://i.imgur.com/npzLQIU.png)

![](https://i.imgur.com/OUhZ8Lj.png)

차이가 생긴 코드 혹은 결과를 함께 공유해 주시면 검토해 보겠습니다.

**Comment by littlehongkong** [comment]
확인 부탁드립니다.
현재 2.26(금) 18시 55분 입니다.

![image](https://user-images.githubusercontent.com/11766241/109285174-13d94180-7864-11eb-9aa5-2a390e3721d0.png)
