### ISSUE TITLE
ETF 종가 데이터 문제

### ISSUE THREAD

**Issue by rudgns3179** [FinanceData/FinanceDataReader#68]
안녕하세요. ETF 종가 데이터 문제 문의드립니다.
2020-11월 이전의 ETF 시고저종 값이 실제 값과 차이가 있습니다.

EX) TIGER 200 (102110)의 경우, 2020-10-05일 시고저종 실제 값이 31050, 31545, 31015, 31435 이지만, fdr.DataReader('102110','2020-10-05','2020-10-08')로 불러와 10월 5일 값을 보면, 30970, 31464, 30935, 31355
이렇게 나옵니다. 

이외에도 다른 ETF에도 이런 현상이 발생하는데 어떻게 된건지 알 수 있을까요??

**Comment by FinanceData** [comment]
우선 현상에 대한 확인을 했습니다.

현재 ETF 데이터를 네이버 파이낸스 차트에서 가져오고 있습니다. 
말씀하신 내용과 같이 일별 데이터와 차트 데이터 사이에 차이가 있습니다.

https://finance.naver.com/item/fchart.nhn?code=102110
![](https://i.imgur.com/rx4W1HY.png)

https://finance.naver.com/item/sise.nhn?code=102110

![](https://i.imgur.com/8OzJxLR.png)

최근 네이버 파이낸스 차트가 바뀌었습니다. 이게 원인인지는 확실치 않습니다만, 이 문제가 계속 된다면 ETF  데이터만 다른 곳에서 가져오도록 개선할 예정입니다.
