### ISSUE TITLE
S&P 지수를 받으면 계속 빈 데이터프레임만 넘어옵니다.

### ISSUE THREAD

**Issue by generpis** [FinanceData/FinanceDataReader#69]
버전은 0.9.12 입니다. 확인 부탁 드립니다.

유용한 패키지 제공에 감사드립니다.

**Comment by FinanceData** [comment]
관심과 수정 제안 감사합니다. 

기능 개선 중에 발생한 오류 이며 0.9.13 에서 FIX 하였습니다.
보다 자세한 내용은 아래 주소를 참고하십시오.

https://github.com/FinanceData/FinanceDataReader/wiki/Release-Note-0.9.13
