### ISSUE TITLE
현재 정상 작동하나요?

### ISSUE THREAD

**Issue by hwanys2** [FinanceData/FinanceDataReader#70]
fdr.StockListing('KRX')

이게 오류가 뜨네요

JSONDecodeError                           Traceback (most recent call last)
<ipython-input-6-78b9c8e45929> in <module>()
      1 
----> 2 krx = fdr.StockListing('KRX')
      3 df_etf = fdr.EtfListing('KR')
      4 df_stock = pd.concat([krx,df_etf], ignore_index=True)
      5 df_stock["종목명"] = df_stock["Name"].str.upper()

/home/pi/.local/lib/python3.7/site-packages/FinanceDataReader/data.py in StockListing(market)
     46         return NaverStockListing(market).read()
     47     if market in [ 'KRX', 'KOSPI', 'KOSDAQ', 'KONEX']:
---> 48         return KrxStockListing(market).read()
     49     if market in [ 'KRX-DELISTING' ]:
     50         return KrxDelisting(market).read()

/home/pi/.local/lib/python3.7/site-packages/FinanceDataReader/krx/listing.py in read(self)
     45         }
     46         r = requests.post(down_url, down_data, headers=header_data)
---> 47         jo = json.loads(r.text)
     48         df_finder = json_normalize(jo, 'block1')
     49         df_finder.columns = ['FullCode', 'ShortCode', 'Name', 'Market']

/usr/lib/python3.7/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    346             parse_int is None and parse_float is None and
    347             parse_constant is None and object_pairs_hook is None and not kw):
--> 348         return _default_decoder.decode(s)
    349     if cls is None:
    350         cls = JSONDecoder

/usr/lib/python3.7/json/decoder.py in decode(self, s, _w)
    335 
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()
    339         if end != len(s):

/usr/lib/python3.7/json/decoder.py in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by keonho-kim** [comment]
비슷한 에러가 발생합니다

저도 비슷한 에러가 발생 중입니다.

--
HTTPError                                 Traceback (most recent call last)
<ipython-input-10-fae2e0e8f5f9> in <module>
----> 1 stocks = fdr.StockListing('KOSPI')

~\anaconda3\lib\site-packages\FinanceDataReader\data.py in StockListing(market)
     46         return NaverStockListing(market).read()
     47     if market in [ 'KRX', 'KOSPI', 'KOSDAQ', 'KONEX']:
---> 48         return KrxStockListing(market).read()
     49     if market in [ 'KRX-DELISTING' ]:
     50         return KrxDelisting(market).read()

~\anaconda3\lib\site-packages\FinanceDataReader\krx\listing.py in read(self)
     21 
     22         url = 'http://kind.krx.co.kr/corpgeneral/corpList.do?method=download&searchType=13'
---> 23         df_listing = pd.read_html(url, header=0)[0]
     24         cols_ren = {'회사명':'Name', '종목코드':'Symbol', '업종':'Sector', '주요제품':'Industry', 
     25                             '상장일':'ListingDate', '결산월':'SettleMonth',  '대표자명':'Representative',

~\anaconda3\lib\site-packages\pandas\util\_decorators.py in wrapper(*args, **kwargs)
    294                 )
    295                 warnings.warn(msg, FutureWarning, stacklevel=stacklevel)
--> 296             return func(*args, **kwargs)
    297 
    298         return wrapper

~\anaconda3\lib\site-packages\pandas\io\html.py in read_html(io, match, flavor, header, index_col, skiprows, attrs, parse_dates, thousands, encoding, decimal, converters, na_values, keep_default_na, displayed_only)
   1084         )
   1085     validate_header_arg(header)
-> 1086     return _parse(
   1087         flavor=flavor,
   1088         io=io,

~\anaconda3\lib\site-packages\pandas\io\html.py in _parse(flavor, io, match, attrs, encoding, displayed_only, **kwargs)
    896 
    897         try:
--> 898             tables = p.parse_tables()
    899         except ValueError as caught:
    900             # if `io` is an io-like object, check if it's seekable

~\anaconda3\lib\site-packages\pandas\io\html.py in parse_tables(self)
    215         list of parsed (header, body, footer) tuples from tables.
    216         """
--> 217         tables = self._parse_tables(self._build_doc(), self.match, self.attrs)
    218         return (self._parse_thead_tbody_tfoot(table) for table in tables)
    219 

~\anaconda3\lib\site-packages\pandas\io\html.py in _build_doc(self)
    734                     pass
    735             else:
--> 736                 raise e
    737         else:
    738             if not hasattr(r, "text_content"):

~\anaconda3\lib\site-packages\pandas\io\html.py in _build_doc(self)
    715         try:
    716             if is_url(self.io):
--> 717                 with urlopen(self.io) as f:
    718                     r = parse(f, parser=parser)
    719             else:

~\anaconda3\lib\site-packages\pandas\io\common.py in urlopen(*args, **kwargs)
    135     import urllib.request
    136 
--> 137     return urllib.request.urlopen(*args, **kwargs)
    138 
    139 

~\anaconda3\lib\urllib\request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    220     else:
    221         opener = _opener
--> 222     return opener.open(url, data, timeout)
    223 
    224 def install_opener(opener):

~\anaconda3\lib\urllib\request.py in open(self, fullurl, data, timeout)
    529         for processor in self.process_response.get(protocol, []):
    530             meth = getattr(processor, meth_name)
--> 531             response = meth(req, response)
    532 
    533         return response

~\anaconda3\lib\urllib\request.py in http_response(self, request, response)
    638         # request was successfully received, understood, and accepted.
    639         if not (200 <= code < 300):
--> 640             response = self.parent.error(
    641                 'http', request, response, code, msg, hdrs)
    642 

~\anaconda3\lib\urllib\request.py in error(self, proto, *args)
    561             http_err = 0
    562         args = (dict, proto, meth_name) + args
--> 563         result = self._call_chain(*args)
    564         if result:
    565             return result

~\anaconda3\lib\urllib\request.py in _call_chain(self, chain, kind, meth_name, *args)
    500         for handler in handlers:
    501             func = getattr(handler, meth_name)
--> 502             result = func(*args)
    503             if result is not None:
    504                 return result

~\anaconda3\lib\urllib\request.py in http_error_302(self, req, fp, code, msg, headers)
    753         fp.close()
    754 
--> 755         return self.parent.open(new, timeout=req.timeout)
    756 
    757     http_error_301 = http_error_303 = http_error_307 = http_error_302

~\anaconda3\lib\urllib\request.py in open(self, fullurl, data, timeout)
    529         for processor in self.process_response.get(protocol, []):
    530             meth = getattr(processor, meth_name)
--> 531             response = meth(req, response)
    532 
    533         return response

~\anaconda3\lib\urllib\request.py in http_response(self, request, response)
    638         # request was successfully received, understood, and accepted.
    639         if not (200 <= code < 300):
--> 640             response = self.parent.error(
    641                 'http', request, response, code, msg, hdrs)
    642 

~\anaconda3\lib\urllib\request.py in error(self, proto, *args)
    561             http_err = 0
    562         args = (dict, proto, meth_name) + args
--> 563         result = self._call_chain(*args)
    564         if result:
    565             return result

~\anaconda3\lib\urllib\request.py in _call_chain(self, chain, kind, meth_name, *args)
    500         for handler in handlers:
    501             func = getattr(handler, meth_name)
--> 502             result = func(*args)
    503             if result is not None:
    504                 return result

~\anaconda3\lib\urllib\request.py in http_error_302(self, req, fp, code, msg, headers)
    753         fp.close()
    754 
--> 755         return self.parent.open(new, timeout=req.timeout)
    756 
    757     http_error_301 = http_error_303 = http_error_307 = http_error_302

~\anaconda3\lib\urllib\request.py in open(self, fullurl, data, timeout)
    529         for processor in self.process_response.get(protocol, []):
    530             meth = getattr(processor, meth_name)
--> 531             response = meth(req, response)
    532 
    533         return response

~\anaconda3\lib\urllib\request.py in http_response(self, request, response)
    638         # request was successfully received, understood, and accepted.
    639         if not (200 <= code < 300):
--> 640             response = self.parent.error(
    641                 'http', request, response, code, msg, hdrs)
    642 

~\anaconda3\lib\urllib\request.py in error(self, proto, *args)
    561             http_err = 0
    562         args = (dict, proto, meth_name) + args
--> 563         result = self._call_chain(*args)
    564         if result:
    565             return result

~\anaconda3\lib\urllib\request.py in _call_chain(self, chain, kind, meth_name, *args)
    500         for handler in handlers:
    501             func = getattr(handler, meth_name)
--> 502             result = func(*args)
    503             if result is not None:
    504                 return result

~\anaconda3\lib\urllib\request.py in http_error_302(self, req, fp, code, msg, headers)
    753         fp.close()
    754 
--> 755         return self.parent.open(new, timeout=req.timeout)
    756 
    757     http_error_301 = http_error_303 = http_error_307 = http_error_302

~\anaconda3\lib\urllib\request.py in open(self, fullurl, data, timeout)
    529         for processor in self.process_response.get(protocol, []):
    530             meth = getattr(processor, meth_name)
--> 531             response = meth(req, response)
    532 
    533         return response

~\anaconda3\lib\urllib\request.py in http_response(self, request, response)
    638         # request was successfully received, understood, and accepted.
    639         if not (200 <= code < 300):
--> 640             response = self.parent.error(
    641                 'http', request, response, code, msg, hdrs)
    642 

~\anaconda3\lib\urllib\request.py in error(self, proto, *args)
    561             http_err = 0
    562         args = (dict, proto, meth_name) + args
--> 563         result = self._call_chain(*args)
    564         if result:
    565             return result

~\anaconda3\lib\urllib\request.py in _call_chain(self, chain, kind, meth_name, *args)
    500         for handler in handlers:
    501             func = getattr(handler, meth_name)
--> 502             result = func(*args)
    503             if result is not None:
    504                 return result

~\anaconda3\lib\urllib\request.py in http_error_302(self, req, fp, code, msg, headers)
    753         fp.close()
    754 
--> 755         return self.parent.open(new, timeout=req.timeout)
    756 
    757     http_error_301 = http_error_303 = http_error_307 = http_error_302

~\anaconda3\lib\urllib\request.py in open(self, fullurl, data, timeout)
    529         for processor in self.process_response.get(protocol, []):
    530             meth = getattr(processor, meth_name)
--> 531             response = meth(req, response)
    532 
    533         return response

~\anaconda3\lib\urllib\request.py in http_response(self, request, response)
    638         # request was successfully received, understood, and accepted.
    639         if not (200 <= code < 300):
--> 640             response = self.parent.error(
    641                 'http', request, response, code, msg, hdrs)
    642 

~\anaconda3\lib\urllib\request.py in error(self, proto, *args)
    561             http_err = 0
    562         args = (dict, proto, meth_name) + args
--> 563         result = self._call_chain(*args)
    564         if result:
    565             return result

~\anaconda3\lib\urllib\request.py in _call_chain(self, chain, kind, meth_name, *args)
    500         for handler in handlers:
    501             func = getattr(handler, meth_name)
--> 502             result = func(*args)
    503             if result is not None:
    504                 return result

~\anaconda3\lib\urllib\request.py in http_error_302(self, req, fp, code, msg, headers)
    742             if (visited.get(newurl, 0) >= self.max_repeats or
    743                 len(visited) >= self.max_redirections):
--> 744                 raise HTTPError(req.full_url, code,
    745                                 self.inf_msg + msg, headers, fp)
    746         else:

HTTPError: HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Moved Temporarily

--

리다이렉트 하는 것에 대해서 문제가 생긴 것 같은데,
지금 한국거래소에 들어갈 수가 없는 것을 보니, 자체적으로 업데이트를 하는 것 같습니다.

아니면 서버가 공격받고 있는 것일수도 있구요.

**Comment by FinanceData** [comment]
관심 감사합니다 (그리고 알려주셔서 감사합니다)

말씀대로 한국거래소가 변경되었습니다.
위 내용은 한국거래소 페이지 개편(공식적으로는 내일 개편)에 따른 변화이며 주말(1/16 토)에 적용되었습니다. 

상세한 내용은 아래 문서를 참고하십시오.

https://github.com/FinanceData/FinanceDataReader/wiki/Release-Note-0.9.14
