### ISSUE TITLE
한국거래소 상장폐지 종목 일봉데이터 수정주가

### ISSUE THREAD

**Issue by ParamountSky** [FinanceData/FinanceDataReader#73]
한국거래소 상장폐지 종목 일봉데이터에 수정주가가 반영되어 있지 않은 것 같은데 반영된 자료는 없을까요?

**Comment by FinanceData** [comment]
거래소 데이터에서 수정주가를 따로 제공하지 않습니다.
상장폐지 일자별 데이터에 상장주식수와 시가총액이 있으므로 수정주가로 계산이 가능합니다.

**Comment by ParamountSky** [comment]
> 거래소 데이터에서 수정주가를 따로 제공하지 않습니다.
> 상장폐지 일자별 데이터에 상장주식수와 시가총액이 있으므로 수정주가로 계산이 가능합니다.

상장폐지 종목 일자별 데이터에 시가총액은 있으나 상장주식수는 없는 것 같습니다.

**Comment by FinanceData** [comment]
아, 그렇군요. DataReader()에는 상장주식수는 없습니다.

종가를 시가총액으로 나누면 상장주식수를 간단하게 구할 수 있습니다.

다음 코드를 참고하시기 바랍니다. 
상장주식수를 구하고 수정종가를 구하는 코드입니다.

```python
# 이매진아시아(036260 ), 2021-02-15 상장폐지
df = fdr.DataReader('036260', exchange='KRX-DELISTING')
df = df.set_index('Date')
df = df.sort_index()
df['Shares'] = df['MarCap'] / df['Close']
df['AdjClose'] = df['Close'] * df.iloc[-1]['Shares'] / df['Shares'] 
```

**Comment by ParamountSky** [comment]
답변 감사합니다. 
1. 코드가 잘 이해가 안되는데요... 원래 종가에 수정비율을 곱해주는 방식 같습니다. 수정비율은 수정주가 이벤트 발생일과 그 전날의 발행주식수의 비율로 계산하면 될텐데 며칠날 수정주가 이벤트가 발생했는지를 위의 데이터만 가지고 알 수 있는지요? 그리고 수정주가 이벤트가 여러번 발생한 경우 첫 이벤트부터 시작해서 누적적으로 적용해야 할 텐데 위의 코드만 봐서는 그런 부분까지 계산이 되는지 잘 모르겠습니다. 
2. 그리고 예전에는 주주명부폐쇄일 다음날 시초가에 강제로 배당금만큼 배당락이 적용됐다고 들었습니다. 이것도 제가 알기론 수정주가에 반영하는 걸로 알고 있는데(https://m.blog.naver.com/ksi0428/221915144028) 이 경우는 상장주식수에 변화가 없어서 수정비율을 구할 수 없지 않을까요? 물론 액면분할 같은 이벤트에 비해면 수정비율이 작아서 굳이 반영을 안해도 백테스팅에 큰 문제는 없을 것 같기는 합니다.

**Comment by FinanceData** [comment]
1.
시총을 종가로 나누어 발행주식수를 구한 것입니다. 발행주식수가 정확하게 계산됩니다.
위 코드로 과거 전체 가격에 누적 반영이 됩니다.


<img src="https://i.imgur.com/FBljISN.png" >


2.
말씀하신 바와 같이 권리락을 반영한 수정주가는 아닙니다.
배당 등의 이벤트를 포함하려면 별도로 배당 데이터를 포함하는 다른 계산이 필요합니다.
말씀하신 바와 같이 액분 등의 이벤트에 비하면 상대적으로 비중이 작아서 감안하고 사용할 수 있을 것 같습니다.
