### ISSUE TITLE
ModuleNotFoundError: No module named 'FinanceDataReader'

### ISSUE THREAD

**Issue by lsj2015-hub** [FinanceData/FinanceDataReader#74]
안녕하세요? 
jupyter notebook상에서 
정상적으로 라이브러리 설치하고( !pip3 install -U finance-datareader)
import FinanceDataReader as fdr 하려니 
ModuleNotFoundError: No module named 'FinanceDataReader' 에러가 뜨네요 ㅠㅠ

terminal에서는 정상적으로 import되어지는데 원인이 뭘까요?

코딩 초짜라서 많이 생소합니다.

참고로 mac 사용하고 있습니다.

**Comment by FinanceData** [comment]
설치 환경을 정확히 알 수 없어서 조금 곤랍합니다만, 우선 다음과 같이 해보세요.
(주피터 노트북 셀에서 pip3 대신 pip 를 써서 설치)

```
!pip install -U finance-datareader
```

Jupyter NotebooK의 커널을 restart 하고 (메뉴: Kernel / restart)
import 해보시기 바랍니다.  

에러 메시지를 그대로 긁어서 올려주시면 더 좋습니다.

**Comment by lsj2015-hub** [comment]
kernel restart해도 안되네여..
에러 메시지는 다음과 같습니다.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-a35580d3be83> in <module>
      2 # 라이브러리의 version을 확인하고 싶을 때는 .__version__으로 확인한다.
      3 
----> 4 import FinanceDataReader as fdr

ModuleNotFoundError: No module named 'FinanceDataReader'

**Comment by FinanceData** [comment]
```
!pip install -U finance-datareader
```

위 명령의 메시지 전체를 올려주시면 도움이 될 것 같습니다.

**Comment by lsj2015-hub** [comment]
jupyter notebook 에 
!pip install -U finance-datareader해서 다음과 같은  메세지가 나왔습니다. 그리고 pandas import까지는 문제없이 됐고
import FinanceDataReader as fdr 하니 위에서 말씀드린  
ModuleNotFoundError: No module named 'FinanceDataReader' 에러가 나온 것입니다.

<!pip install -U finance-datareader> 메세지 내용

Requirement already satisfied: finance-datareader in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (0.9.20)
Collecting finance-datareader
  Downloading finance_datareader-0.9.31-py3-none-any.whl (17 kB)
Requirement already satisfied: requests-file in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from finance-datareader) (1.5.1)
Requirement already satisfied: pandas>=0.19.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from finance-datareader) (1.2.2)
Requirement already satisfied: tqdm in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from finance-datareader) (4.57.0)
Requirement already satisfied: requests>=2.3.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from finance-datareader) (2.25.1)
Requirement already satisfied: lxml in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from finance-datareader) (4.6.2)
Requirement already satisfied: numpy>=1.16.5 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pandas>=0.19.2->finance-datareader) (1.20.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pandas>=0.19.2->finance-datareader) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pandas>=0.19.2->finance-datareader) (2021.1)
Requirement already satisfied: six>=1.5 in /Users/seanlee/Library/Python/3.9/lib/python/site-packages (from python-dateutil>=2.7.3->pandas>=0.19.2->finance-datareader) (1.15.0)
Requirement already satisfied: chardet<5,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from requests>=2.3.0->finance-datareader) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from requests>=2.3.0->finance-datareader) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from requests>=2.3.0->finance-datareader) (1.26.2)
Requirement already satisfied: idna<3,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from requests>=2.3.0->finance-datareader) (2.10)
Installing collected packages: finance-datareader
  Attempting uninstall: finance-datareader
    Found existing installation: finance-datareader 0.9.20
    Uninstalling finance-datareader-0.9.20:
      Successfully uninstalled finance-datareader-0.9.20
Successfully installed finance-datareader-0.9.31

**Comment by wlstjdpark** [comment]
저도 같은 문제가 발생했다가 해결한 내용 공유 드립니다.

우선 저는 M1 SigSur 환경입니다.
기본적으로 python2 이 설치되어있는 상태로  python3.9을 설치 했다가,
다시 python2 을 지우고 python3.9도 지운 다음에 python3.8로 재설치 했습니다.
그 중간 과정에 jupyterlab 을 설치 했었는데요, pip list 를 해보니 jupyterlab이 없다는 걸 확인 하고
기존에 설치 되어있는 jupyter를 완전 제거하고 다시 pip install jupyterlab 하여 실행하니 잘 동작했습니다.

말이 길었는데 요약하자면.. 터미널에서
- which jupyter
- rm -rf 경로 (또는 rm -rf $(which jupyter)
위 명령어를 통해 나온 경로의 내용을 아래와 같이 완전 삭제
- pip install jupyterlab
- jupyter lab 실행

해결이 되길 바래봅니다!

**Comment by WS-200099** [comment]
我整了4个小时终于知道什么问题了，原来是你这个模块没写对名字啊，import FinanceDataReader as fdr才是正确的，你忘记大写了
