### ISSUE TITLE
당일 거래량 차이

### ISSUE THREAD

**Issue by pelorz** [FinanceData/FinanceDataReader#75]
안녕하세요.
어제, 오늘 거래량을 확인해 봤는데, 자정이 다 되어가도 전체 거래량이 실제 전체 거래량보다 적습니다.
익일 오전에는 반영이 되는 것 같은데요. 업데이트 시간을 당일에 업데이트가 되도록 수정 가능할까요? 

예) 21-02-18 23:08시 기준 삼성전자 당일 거래량 : 2,1327,683 , 현시점 라이브러리 거래량 : 21,068,332

**Comment by FinanceData** [comment]
업데이트에 시간차(10초 이내) 정도의 차이가 있기는 하지만 정확하게 업데이트 되는 것을 확인하였습니다.
2021. 02. 25. (목) 14:45:04 KST 장중 데이터 입니다. 

<img src="https://i.imgur.com/2Uji7ad.png" >

<img src="https://i.imgur.com/ALZKCSR.png" >

일시적인 현상일 수 있으니,
추가적인 확인을 해봐 주시면 감사합니다.

참고 fdr의 국내 가격 데이터는 네이버 증권의 데이터 입니다.

**Comment by pelorz** [comment]
안녕하세요.
오늘 장종료후 확인했는데 업데이트가 잘 되어있어서 들어왔습니다. 
좋은 라이브러리 감사합니다. 수고하세요.

**Comment by FinanceData** [comment]
관심 감사합니다. 도움이 되셨길 바랍니다.
