### ISSUE TITLE
df = fdr.DataReader('US10YT=RR') # 10년 만기 미국국채 수익률 오류

### ISSUE THREAD

**Issue by TAEYOUKIM** [FinanceData/FinanceDataReader#80]
안녕하세요 항상 잘 사용하고 있습니다. 요즘 이슈인 10년 만기 미국국채 수익률에서 에러가 있네요. 확인가능할까요?

좋은 API 제공해주셔서 감사합니다. 

ValueError                                Traceback (most recent call last)
<ipython-input-21-8a9807d2e2d4> in <module>()
----> 1 df = fdr.DataReader('US10YT=RR') # 10년 만기 미국국채 수익률

2 frames
/usr/local/lib/python3.7/dist-packages/FinanceDataReader/investing/data.py in _get_currid_investing(self, symbol, exchange, data_source)
     54 
     55         if len(df) == 0:
---> 56             raise ValueError(f"Symbol('{symbol}'), Exchange('{exchange}') not found")
     57         return df.iloc[0]['pairId']
     58 

**ValueError: Symbol('US10YT=RR'), Exchange('None') not found**

**Comment by TAEYOUKIM** [comment]
![image](https://user-images.githubusercontent.com/44917050/109248152-dea70200-7817-11eb-838a-30ec1bbb2533.png)
Investing.com 쪽에서 'US10YT=RR'이 아니라 'US10YT=X'로 변경한듯합니다.
메인 튜토리얼쪽에서 수정되면 될거같아요

**Comment by FinanceData** [comment]
@TAEYOUKIM 님께서 언급하신 것과 같이 심볼의 변화가 있었습니다. 다음과 같이 문서를 수정하였습니다.

```python
## 채권 수익률
df = fdr.DataReader('KR1YT=RR') # 1년만기 한국국채 수익률
df = fdr.DataReader('KR10YT=RR') # 10년만기 한국국채 수익률

df = fdr.DataReader('US1MT=X') # 1개월 만기 미국국채 수익률
df = fdr.DataReader('US10YT=X') # 10년 만기 미국국채 수익률
```

**Comment by FinanceData** [comment]
관련하여 Quick-Reference 내용도 업데이트 하였습니다.

https://github.com/FinanceData/FinanceDataReader/wiki/Quick-Reference
