### ISSUE TITLE
KQ150에 대한 지수데이터 확인 부탁드립니다.

### ISSUE THREAD

**Issue by littlehongkong** [FinanceData/FinanceDataReader#81]
확인 부탁드립니다.
현재 2.26(금) 18시 55분 입니다.

![image](https://user-images.githubusercontent.com/11766241/109285174-13d94180-7864-11eb-9aa5-2a390e3721d0.png)

_Originally posted by @littlehongkong in https://github.com/FinanceData/FinanceDataReader/issues/67#issuecomment-786539884_

**Comment by FinanceData** [comment]
FinanceDataReader 는 investing.com 의 데이터를 크롤링 합니다. investing.com 의 집계 방식에 의한 한계(지연)로 보입니다.

현재 시간 2021-02-26 19:51 입니다.

https://kr.investing.com/indices/kosdaq-150-historical-data

<img src="https://i.imgur.com/p8iG1nN.png" >

**Comment by FinanceData** [comment]
국내지수에 대해서는 한국거래소(KRX)의 다양한 지수를 별도로 지원할 계획을 가지고 있습니다.
