### ISSUE TITLE
주식 가격 은 수정주가가 반영 된것 같은데.. 거래량은 안된것 같습니다.

### ISSUE THREAD

**Issue by microfun** [FinanceData/FinanceDataReader#85]
![image](https://user-images.githubusercontent.com/17971164/110043541-e6702480-7d8a-11eb-8c0c-f29b3dbe8f55.png)

삼성전자 주식 데이터를 1997년 03-15 데이터를 받아서 크레온 데이터를 비교해 봤을때.
가격은 수정주가가 반영되어 나오는것을 확인 했지만, 거래량은 반영이 안되어 있는것 같습니다.
3월 15일 : 크레온 1752000  --> 35040
3월 17일 : 크레온 3203500 --> 64070 
약 50배.. 차이가 나는것 같은데요.. 
확인 부탁 드립니다.

**Comment by FinanceData** [comment]
거래량(Volume)은 거래주식수로 데이터가 제공됩니다. (수정거래주식수가 아닌 일반 거래주식수 입니다) 
한국거래소, 네이버 증권(일별 시세, 차트) 등 도 모두 거래량은 주식수로 제공하고 있습니다.

<img src="https://i.imgur.com/kUnayj9.png" >

FinanceDataReader 에서 자체적으로 데이터를 가공하는 것이 아니기 때문에 거래량을 수정 거래량으로 제공하는 것을 어렵습니다.

**Comment by jaepil-choi** [comment]
일반 증권사 어플들도 다 raw volume으로 제공하고 있네요. 

하지만 야후 파이넌스도, investing.com도 차트에 모두 adjusted volume으로 제공하고 있습니다. 

만약 `FinanceDataReader`나 기타 국내 증권사 어플처럼 adj close price는 제공하면서 volume은 raw volume으로 제공한다면 직접 adjusted volume을 구하기 위해 주식 분할이 일어난 시점마다 split factor를 거래량에 곱해주는 과정이 필요한데 왜 고쳐지지 않는지 의아하네요. 

이해를 돕기 위해 한투어플에서 캡쳐한 AAPL의 주가/거래량 차트와 같은기간 Yahoo Finance, Investing.com에서 캡쳐한 AAPL의 주가/거개량 차트를 첨부합니다. 

![image](https://user-images.githubusercontent.com/25889304/120528481-7a976980-c416-11eb-84e1-dcf6ea225708.png)
한투 어플

![image](https://user-images.githubusercontent.com/25889304/120528630-a31f6380-c416-11eb-9188-20739c6a1782.png)
야후 파이넌스

![image](https://user-images.githubusercontent.com/25889304/120528735-bf230500-c416-11eb-8bb1-5e29d06c4a0e.png)
인베스팅닷컴
