### ISSUE TITLE
베트남 거래소 일부종목에 주가데이터가 누락되어 있습니다.

### ISSUE THREAD

**Issue by anite2** [FinanceData/FinanceDataReader#89]
'DAG' 동아플라스틱이라는 종목은 주가데이터가 없네요

그리고 주가데이터를 다운받아보면 중간에 결측치가 많습니다. ㅜㅠ

**Comment by limsh87** [comment]
글이 안올라가서 여기 댓글로 달아봅니다. 해외주식 가격데이터 조회시 2018년 이후 가격데이터가 조회가 안됩니다.

**Comment by FinanceData** [comment]
업데이트 버전에서 데이터 소스 등을 정리하였습니다.
DAG 는 아래와 같이 조회해보세요.

```python
df = fdr.DataReader('HOSE:DAG')
```

FinanceDataReader는 데이터를 Yahoo 에서 가져오는데요 데이터의 결측치 등은 원천데이터(Yahoo finance)에서 결측치가 있거나 한 경우일 겁니다.

예를 들어, 

https://finance.yahoo.com/quote/VCB.VN/history?p=VCB.VN
![image](https://github.com/FinanceData/FinanceDataReader/assets/806717/24900f52-0078-4308-b534-c6e7f75cdc95)

위 경우 국경일등이 있어서 결측치가 발생합니다. 데이터를 yahoo 에서가져옵니다. 원천 데이터가 누락된 경우가 대부분입니다.

**Comment by FinanceData** [comment]
업데이트에서 확인후 FIX

[Release Note 0.9.61](https://github.com/FinanceData/FinanceDataReader/wiki/Release-Note-0.9.61)
