### ISSUE TITLE
버그: 데이터 이상 (종종 거래량 차이가 크게 나타남)

### ISSUE THREAD

**Issue by FinanceData** [FinanceData/FinanceDataReader#9]
데이터의 경우 거래량의 차이가 종종 크게 나타남, 

삼성전자(005930) 18.05.31 예시

### daum.net
```
18.06.01	50,500	51,700	49,950	51,300	600	+1.18%	13,038,499
18.05.31	50,400	50,800	49,850	50,700	1,200	+2.42%	63,491,109
18.05.30	51,300	51,500	49,100	49,500	1,800	-3.51%	20,498,098
```

### investing.com 
```
Jun 01, 2018	51,300	50,500	51,700	49,950	12.44M	1.18%
May 31, 2018	50,700	50,400	50,800	49,850	35.94M	2.42%
May 30, 2018	49,500	51,300	51,500	49,100	20.20M	-3.51%
```

**Comment by finetea** [comment]
> 데이터의 경우 거래량의 차이가 종종 크게 나타남,
> 
> 삼성전자(005930) 18.05.31 예시
> 
> ### daum.net
> ```
> 18.06.01	50,500	51,700	49,950	51,300	600	+1.18%	13,038,499
> 18.05.31	50,400	50,800	49,850	50,700	1,200	+2.42%	63,491,109
> 18.05.30	51,300	51,500	49,100	49,500	1,800	-3.51%	20,498,098
> ```
> ### investing.com
> ```
> Jun 01, 2018	51,300	50,500	51,700	49,950	12.44M	1.18%
> May 31, 2018	50,700	50,400	50,800	49,850	35.94M	2.42%
> May 30, 2018	49,500	51,300	51,500	49,100	20.20M	-3.51%
> ```

naver, yahoo finance 공히 아래와 같이 데이터가 나오는데 investing.com만 위와 같이 차이나게 나오는 것을 보니 investing.com의 데이터가 뭔가 문제가 있지 않나 생각합니다. 
Jun 01, 2018 | 50,500.00 | 51,700.00 | 49,950.00 | 51,300.00 | 50,540.97 | 13,038,499
May 31, 2018 | 50,400.00 | 50,800.00 | 49,850.00 | 50,700.00 | 49,949.85 | 63,491,109
May 30, 2018 | 51,300.00 | 51,500.00 | 49,100.00 | 49,500.00 | 48,767.60 | 20,498,098

다른 예시가 더 있나요?

**Comment by FinanceData** [comment]
Investing 의 국내 종목 가격 데이터의 경우 수정 가격이 제대로 반영이 매우 늦으며, 반영되지 않은 데이터(예: 거래량)에 종종 나타납니다.

이 문제를 해결하고 수정 가격을 지원하기 위해 국내 종목 가격은 Naver 에서 가져오는 것으로 수정하였습니다.

https://github.com/FinanceData/FinanceDataReader/wiki/Release-Note-0.7.1

**Comment by finetea** [comment]
아.. 그랬군요. ^^
FinanceDataReader 정말 잘 만드신 것 같습니다. 최근에 발견해서 잘 사용하고 있습니다. 저도 도울만한 부분 있으면 참여하도록 하겠습니다. 감사합니다. :)
