### ISSUE TITLE
lxml not found

### ISSUE THREAD

**Issue by organicpython** [FinanceData/FinanceDataReader#97]
안녕하세요 만드신 프로그램 잘 쓰고 있습니다.

삼성전자와 같은 국내 주식을 조회할 때는 잘 작동되나
IXIC나 VIX같은 해외 데이터를 조회할 때 importerror: lxml not found, please install it 
이라는 오류가 나오는 것 같습니다.
python은 32bit 3.8이고, lxml은 현재 4.6.3 입니다.

**Comment by FinanceData** [comment]
lxml이 설치되어 있다는 말씀이신듯 합니다. 가상환경 등도 함께 확인 부탁드립니다.
다음과 같이 확인해 보시는 것을 추천 드립니다.

```python
import lxml
```

PS.
너무 지연되어 회신을 드려 죄송합니다. 문제가 없다면 현 이슈를 Close 하겠습니다.
